import { mkdtemp, readFile, rm, writeFile } from "node:fs/promises";
import { readFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join, resolve } from "node:path";
import { describe, expect, it } from "vitest";
import { createLocalRuntime } from "../packages/local-runtime/src/runtime.js";
import { RunFileStore } from "../packages/local-runtime/src/storage/run-file-store.js";
import type { Scenario } from "../packages/contracts/src/index.js";

const root = resolve(import.meta.dirname, "..");
const dataDir = resolve(root, "data");
async function fixture() { const dir = await mkdtemp(join(tmpdir(), "viseca-recovery-")); const options = { rootDir: root, dataDir, stateDir: join(dir, "state"), outputDir: join(dir, "output"), createKey: () => "RECOVERY1" }; const runtime = await createLocalRuntime(options); const scenario = runtime.pack.scenarios[0] as Scenario; const draft = await runtime.policies.createDraft(scenario.scenario_id, { instruction: scenario.cardholder_instruction, hard_rules: [], uncertainty_policy: "ask", guidance: [], open_questions: [] }); const mandate = await runtime.policies.confirmDraft(draft.draft_id, "test_script"); const view = await runtime.runs.create({ scenario_id: scenario.scenario_id, mandate_id: mandate.mandate_id, mode: "inspection" }); return { dir, options, runtime, view }; }

describe("inspection recovery", () => {
  it("does not treat the output audits sidecar as a run", async () => { const directory = await mkdtemp(join(tmpdir(), "viseca-discovery-")); await (await import("node:fs/promises")).mkdir(join(directory, "audits"), { recursive: true }); await writeFile(join(directory, "audits", "README.md"), "sidecar"); await expect(new RunFileStore(directory).loadAll()).resolves.toEqual([]); await rm(directory, { recursive: true, force: true }); });
  it("rejects a run-shaped directory without its canonical snapshot", async () => { const directory = await mkdtemp(join(tmpdir(), "viseca-discovery-")); await (await import("node:fs/promises")).mkdir(join(directory, "LOCAL_RUN_MISSING"), { recursive: true }); await expect(new RunFileStore(directory).loadAll()).rejects.toMatchObject({ code: "run_store_invalid" }); await rm(directory, { recursive: true, force: true }); });
  it.each(["after_snapshot", "after_events", "after_traces"])("recovers a write fault at %s without duplicating the event", async (fault) => { const f = await fixture(); const service = f.runtime.runs as unknown as { store: { fault?: (point:string)=>void } }; let armed=true;service.store.fault=(point)=>{if(armed&&point===fault){const durable=JSON.parse(readFileSync(join(f.options.outputDir,f.view.run.run_id,'run.json'),'utf8'));if(durable.run.emitted_count===1){armed=false;throw new Error(fault);}}}; await expect(f.runtime.runs.next(f.view.run.run_id, `fault-${fault}`)).rejects.toThrow(fault); const restarted = await createLocalRuntime(f.options); const recovered = await restarted.runs.next(f.view.run.run_id, `fault-${fault}`); expect(recovered.authorization).not.toBeNull(); expect(recovered.view.counts.emitted).toBe(1); const lines = (await readFile(join(f.options.outputDir, f.view.run.run_id, "events.jsonl"), "utf8")).trim().split("\n"); expect(lines).toHaveLength(1); await rm(f.dir, { recursive: true, force: true }); });
  it("replays the same idempotency key after restart without a second event", async () => { const f = await fixture(); const first = await f.runtime.runs.next(f.view.run.run_id, "recover-key"); const restarted = await createLocalRuntime(f.options); const second = await restarted.runs.next(f.view.run.run_id, "recover-key"); expect(second.authorization?.authorization_id).toBe(first.authorization?.authorization_id); expect(second.view.counts.emitted).toBe(1); const lines = (await readFile(join(f.options.outputDir, f.view.run.run_id, "events.jsonl"), "utf8")).trim().split("\n"); expect(lines).toHaveLength(1); await rm(f.dir, { recursive: true, force: true }); });
  it("rejects an incomplete canonical event before runtime publication", async () => { const f = await fixture(); const first = await f.runtime.runs.next(f.view.run.run_id, "corrupt-key"); const path = join(f.options.outputDir, f.view.run.run_id, "run.json"); const state = JSON.parse(await readFile(path, "utf8")) as { records: Array<{ event: { authorization: { items?: unknown } } }> }; delete state.records[0]!.event.authorization.items; await writeFile(path, JSON.stringify(state)); await expect(createLocalRuntime(f.options)).rejects.toMatchObject({ code: "run_store_invalid" }); await rm(f.dir, { recursive: true, force: true }); });
  it("keeps trace sequences unique across a recovered command", async () => { const f = await fixture(); await f.runtime.runs.next(f.view.run.run_id, "trace-key"); const restarted = await createLocalRuntime(f.options); await restarted.runs.next(f.view.run.run_id, "trace-key"); const traces = (await readFile(join(f.options.outputDir, f.view.run.run_id, "trace.jsonl"), "utf8")).trim().split("\n").map((line) => JSON.parse(line) as { sequence: number }); expect(new Set(traces.map((trace) => trace.sequence)).size).toBe(traces.length); await rm(f.dir, { recursive: true, force: true }); });
});
