import {expect,it} from 'vitest';
import {fixture} from './simulation-fixture.js';
import {assess} from '../packages/local-runtime/src/simulation/evaluator.js';
import {liveAssessment} from '../packages/local-runtime/src/services/wallet-service.js';
import type {LiveEntry} from '../packages/local-runtime/src/simulation/viseca-worker.js';
import type {Assessment} from '../packages/contracts/src/simulation.js';
function pending():LiveEntry {const ctx=fixture();ctx.config.parameters.always_ask=true;const assessment=assess(ctx);expect(assessment.questions.length).toBeGreaterThan(0);return {id:ctx.event.authorization.authorization_id,event:ctx.event,state:'awaiting_human',reserved:true,snapshot:{},proposal:{decision:'step_up',snapshot:assessment},intent:null,accepted:{decision:'step_up',at:ctx.now,response:{}},human_expires_at:new Date(Date.parse(ctx.now)+120000).toISOString(),history:[]};}
it('projects the accepted live deadline instead of the earlier proposal deadline',()=>{const e=pending();const a=e.proposal!.snapshot as Assessment;const original=a.lock!.expires_at!;e.human_expires_at=new Date(Date.parse(original)+25000).toISOString();const view=liveAssessment(e,Date.parse(original)+1000)!;expect(view.execution_state).toBe('awaiting_user');expect(view.lock!.expires_at).toBe(e.human_expires_at);expect(a.lock!.expires_at).toBe(original);});
it.each(['approve','decline'] as const)('projects accepted %s without stale questions or confirmation controls',decision=>{const entry=pending();entry.accepted!.decision=decision;entry.reserved=false;entry.state='accepted';const view=liveAssessment(entry);expect(view).toMatchObject({execution_state:decision==='approve'?'approved':'declined',decision:decision==='approve'?'approve':'deny',questions:[],lock:null,can_finalize:false});expect((entry.proposal!.snapshot as {questions:unknown[]}).questions.length).toBeGreaterThan(0);});
it('hides expired live confirmation controls while retaining the remote reservation until reconciliation',()=>{const entry=pending();const view=liveAssessment(entry,Date.parse(entry.human_expires_at!));expect(view).toMatchObject({execution_state:'expired',decision:null,questions:[],lock:null,can_finalize:false});expect(entry.reserved).toBe(true);expect(entry.accepted!.decision).toBe('step_up');});
