import { describe,expect,it } from 'vitest';
import { fixture } from './simulation-fixture.js';
import { evaluateLive,validateLiveBinding } from '../packages/local-runtime/src/simulation/live-engine.js';
import { hash } from '../packages/local-runtime/src/simulation/common.js';
import type { LiveBinding } from '../packages/local-runtime/src/simulation/live-engine.js';
const binding=(c:Awaited<ReturnType<typeof fixture>>):LiveBinding=>({config:c.config,live_mandate_id:c.event.mandate.mandate_id,scenario_id:c.event.authorization.scenario_id,hard_rules:c.event.mandate.hard_rules,history_hash:hash(c.pack.history),pack_version:c.pack.pack_version});
const entry=(c:Awaited<ReturnType<typeof fixture>>,decision:'approve'|'decline'|undefined,reserved=false)=>({id:'OLD',event:c.event,state:'awaiting_human' as const,...(decision?{decision}:{}),reserved,snapshot:{},proposal:null,intent:null,accepted:decision?{decision,at:c.now,response:{}}:null,human_expires_at:null,history:[]});
describe('live engine',()=>{
 it('validates confirmed binding and proposes ordinary approval',async()=>{const c=await fixture('AU0004');const b=binding(c);expect(validateLiveBinding(b,c.pack).live_mandate_id).toBe(c.event.mandate.mandate_id);const r=evaluateLive(c.pack,b,c.event,'LIVE',[],c.now);expect(r.decision).toBe('approve');});
 it('holds snapshot mismatch technically',async()=>{const c=await fixture('AU0004');const b=binding(c);const e=structuredClone(c.event);e.mandate.instruction='changed';expect(evaluateLive(c.pack,b,e,'LIVE',[],c.now).reason_codes).toContain('G05_LIVE_SNAPSHOT_MISMATCH');});
 it('counts accepted prior approval in rolling budget',async()=>{const c=await fixture('AU0004');c.config.parameters.max_order_chf='1000';c.config.parameters.rolling_budget={limit_chf:'200',days:7};const b=binding(c);const r=evaluateLive(c.pack,b,c.event,'LIVE',[{...entry(c,'approve'),accepted:{decision:'approve',at:c.now,response:{}},event:{...c.event,authorization:{...c.event.authorization,authorization_id:'OLD' as never,billing_amount_chf:100}}}],c.now);expect(r.reason_codes).toContain('C10_ROLLING_BUDGET_EXCEEDED');expect(r.decision).toBe('deny');});
 it('unknown prior proposal holds reserved capacity without asking for customer evidence',async()=>{const c=await fixture('AU0004');c.config.parameters.max_order_chf='1000';c.config.parameters.rolling_budget={limit_chf:'200',days:7};const b=binding(c);const r=evaluateLive(c.pack,b,c.event,'LIVE',[{...entry(c,undefined,true),event:{...c.event,authorization:{...c.event.authorization,authorization_id:'OLD' as never,billing_amount_chf:100}}}],c.now);expect(r.decision).toBeNull();expect(r.snapshot).toMatchObject({execution_state:'technical_hold',technical_filter_ids:expect.arrayContaining(['C12']),questions:[]});expect(r.reason_codes).toContain('C12_BUDGET_RESERVED_ELSEWHERE');expect(r.reason_codes).not.toContain('C10_ROLLING_BUDGET_EXCEEDED');});
 it('rejects changed hard-rule binding',async()=>{const c=await fixture('AU0004');const b=binding(c);b.hard_rules=[{field:'x',operator:'=',value:'y'}];expect(()=>validateLiveBinding(b,c.pack)).toThrow('live_unsupported_rule');expect(evaluateLive(c.pack,b,c.event,'LIVE',[],c.now).reason_codes).toContain('G05_LIVE_SNAPSHOT_MISMATCH');});
});
