import { describe,expect,it } from 'vitest';
import { mkdtemp,writeFile } from 'node:fs/promises';import { join } from 'node:path';import { tmpdir } from 'node:os';
import { DatabaseSync } from 'node:sqlite';
import { SimulationStore } from '../packages/local-runtime/src/simulation/store.js';
import { hash } from '../packages/local-runtime/src/simulation/common.js';
const valid=(x:unknown)=>{if(!x||typeof x!=='object')throw Error('invalid');};
async function path(){return join(await mkdtemp(join(tmpdir(),'sim-store-')),'state.sqlite');}
describe('SimulationStore durability',()=>{
 it.each(['before_write','after_write'] as const)('rolls back state and command at %s',async point=>{const p=await path();let visited=false;const s=new SimulationStore(p,valid,at=>{if(at===point){visited=true;throw Error(point);}});expect(()=>s.transaction(point,point,state=>{state.configs.push({} as never);return point;})).toThrow(point);expect(visited).toBe(true);expect(s.read().commands[point]).toBeUndefined();expect(s.select(state=>state.configs)).toEqual([]);s.close();const db=new DatabaseSync(p);expect(db.prepare('SELECT count(*) AS n FROM commands').get()!['n']).toBe(0);db.close();});
it('replays after commit fault exactly once',async()=>{const p=await path();const s=new SimulationStore(p,valid,point=>{if(point==='after_commit')throw Error('after')});expect(()=>s.transaction('k',{x:1},()=>({ok:true}))).toThrow();expect(s.transaction('k',{x:1},()=>({ok:false}))).toEqual({ok:true});expect(s.read().commands['k']).toBeDefined();s.close();});
 it('rejects conflicting idempotency body',async()=>{const s=new SimulationStore(await path(),valid);s.transaction('k',{x:1},()=>1);expect(()=>s.transaction('k',{x:2},()=>2)).toThrow(/different content/);s.close();});
 it('reopens committed command',async()=>{const p=await path();let s=new SimulationStore(p,valid);s.transaction('k',{x:1},()=>7);s.close();s=new SimulationStore(p,valid);expect(s.transaction('k',{x:1},()=>0)).toBe(7);s.close();});
 it('keeps the canonical body bounded while retaining exact command replay',async()=>{const p=await path();const s=new SimulationStore(p,valid);s.transaction('large',{x:1},()=>({payload:'x'.repeat(100000)}));s.close();const db=new DatabaseSync(p);const body=String(db.prepare('SELECT body FROM state WHERE id=1').get()!['body']);expect(body).not.toContain('x'.repeat(1000));expect(db.prepare('SELECT count(*) AS n FROM commands').get()!['n']).toBe(1);db.close();});
 it('migrates legacy inline commands without losing replay',async()=>{const p=await path();const db=new DatabaseSync(p);db.exec('CREATE TABLE state (id INTEGER PRIMARY KEY, revision INTEGER, body TEXT, checksum TEXT)');const legacy={schema_version:1,configs:[],runs:[],commands:{legacy:{fingerprint:hash({a:1}),response:{ok:true}}}};db.prepare('INSERT INTO state VALUES(1,0,?,?)').run(JSON.stringify(legacy),hash(legacy));db.close();const s=new SimulationStore(p,valid);expect(s.transaction('legacy',{a:1},()=>({ok:false}))).toEqual({ok:true});s.close();});
 it('reports checksum corruption as 503',async()=>{const p=await path();const s=new SimulationStore(p,valid);s.close();await writeFile(p,'corrupt');expect(()=>new SimulationStore(p,valid)).toThrow();});
});

it('cached projections detect external writes and keep returned values isolated',async()=>{const p=await path();let validations=0;const s=new SimulationStore(p,()=>{validations++;});const before=validations;const a=s.select(state=>state.configs);a.push({} as never);expect(s.select(state=>state.configs)).toEqual([]);expect(validations).toBe(before);const writer=new DatabaseSync(p);writer.prepare('UPDATE state SET body=? WHERE id=1').run('{"schema_version":1,"configs":[{}],"runs":[],"commands":{}}');writer.close();expect(()=>s.select(state=>state.runs)).toThrow('could not be verified');s.close();});

it('refuses a corrupted legacy ledger before migrating or changing its checksum',async()=>{const p=await path();const original={schema_version:1,configs:[],runs:[],commands:{legacy:{fingerprint:hash({}),response:9}}};const db=new DatabaseSync(p);db.exec('CREATE TABLE state(id INTEGER PRIMARY KEY,revision INTEGER,body TEXT,checksum TEXT)');db.prepare('INSERT INTO state VALUES(1,0,?,?)').run(JSON.stringify(original),'bad-checksum');db.close();expect(()=>new SimulationStore(p,valid)).toThrow('could not be verified');const check=new DatabaseSync(p);expect(check.prepare('SELECT checksum FROM state').get()!['checksum']).toBe('bad-checksum');expect(check.prepare('SELECT count(*) AS n FROM commands').get()!['n']).toBe(0);check.close();});
it('refuses conflicting legacy command rows without discarding the old ledger',async()=>{const p=await path();const s=new SimulationStore(p,valid);s.transaction('k',{},()=>1);s.close();const db=new DatabaseSync(p);const legacy={schema_version:1,configs:[],runs:[],commands:{k:{fingerprint:hash({}),response:2}}};db.prepare('UPDATE state SET body=?,checksum=?').run(JSON.stringify(legacy),hash(legacy));db.close();expect(()=>new SimulationStore(p,valid)).toThrow('could not be verified');const check=new DatabaseSync(p);expect(JSON.parse(String(check.prepare('SELECT body FROM state').get()!['body'])).commands.k.response).toBe(2);check.close();});
it('verifies command integrity on replay without loading the journal for normal projections',async()=>{const p=await path();const s=new SimulationStore(p,valid);s.transaction('k',{},()=>({approved:true}));const db=new DatabaseSync(p);db.prepare('UPDATE commands SET response=? WHERE key=?').run(JSON.stringify({response:{approved:false}}),'k');db.close();expect(s.select(state=>state.runs)).toEqual([]);expect(()=>s.transaction('k',{},()=>null)).toThrow('could not be verified');expect(()=>s.read()).toThrow('could not be verified');s.close();});
it('keeps projections free of journal responses across many writes and a restart',async()=>{const p=await path();let s=new SimulationStore(p,valid);for(let i=0;i<25;i++)s.transaction(String(i),{i},()=>({i,payload:'x'.repeat(10000)}));expect(s.select(state=>Object.keys(state.commands))).toEqual([]);s.close();s=new SimulationStore(p,valid);expect(s.transaction('0',{i:0},()=>null)).toEqual({i:0,payload:'x'.repeat(10000)});expect(Object.keys(s.read().commands)).toHaveLength(25);s.close();const db=new DatabaseSync(p);expect(String(db.prepare('SELECT body FROM state').get()!['body']).length).toBeLessThan(100);db.close();});
it('replays a void command after reopening',async()=>{const p=await path();let s=new SimulationStore(p,valid);s.transaction('void',{},()=>undefined);s.close();s=new SimulationStore(p,valid);expect(s.transaction('void',{},()=>3)).toBeUndefined();s.close();});
