import { mkdtemp,rm } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join,resolve } from 'node:path';
import { afterEach,it,expect } from 'vitest';
import { createLocalApp } from '../apps/local-web/src/app.js';
import type { FastifyInstance } from 'fastify';
import type { SafetyConfig,SimRun,Assessment } from '../packages/contracts/src/simulation.js';
import type { ScenarioDetail,MandateRecord,PolicyDraft } from '../packages/contracts/src/index.js';
import { validateLiveBinding } from '../packages/local-runtime/src/simulation/live-engine.js';
import { loadDataPack } from '../packages/local-runtime/src/data/index.js';
const apps:FastifyInstance[]=[],dirs:string[]=[];
afterEach(async()=>{for(const a of apps.splice(0))await a.close();for(const d of dirs.splice(0))await rm(d,{recursive:true,force:true});});
async function setup(always=false){let now=new Date('2026-09-19T00:00:00.000Z');const dir=await mkdtemp(join(tmpdir(),'mcg-http-'));dirs.push(dir);const app=await createLocalApp({now:()=>now,stateDir:join(dir,'state'),outputDir:join(dir,'output'),webDir:resolve('apps/local-web/web')});apps.push(app);const detail=(await app.inject('/api/scenarios/SCEN0000')).json<ScenarioDetail>();const p=detail.initial_policy;const draftResponse=await app.inject({method:'POST',url:'/api/mandate-drafts',headers:{'idempotency-key':'draft001'},payload:{scenario_id:'SCEN0000',instruction:p.instruction,hard_rules:[],uncertainty_policy:'ask',guidance:[],open_questions:[]}});expect(draftResponse.statusCode).toBe(201);const draft=draftResponse.json<PolicyDraft>();const m=(await app.inject({method:'POST',url:`/api/mandate-drafts/${draft.draft_id}/confirm`,headers:{'idempotency-key':'confirm01'},payload:{confirmed:true}})).json<MandateRecord>();const cfg=(await app.inject({method:'POST',url:`/api/mandates/${m.mandate_id}/safety-configs`,headers:{'idempotency-key':'config001'},payload:{}})).json<SafetyConfig>();const session=await app.inject(`/api/ui-session?mandate_id=${m.mandate_id}`);const cookie=String(session.headers['set-cookie']).split(';')[0]!;const csrf=session.json<{csrf:string}>().csrf;const headers={cookie,'x-csrf-token':csrf};const confirmed=await app.inject({method:'POST',url:`/api/safety-configs/${cfg.config_id}/confirm`,headers:{...headers,'idempotency-key':'review001'},payload:{parameters:{...cfg.parameters,domestic_country:'CH',always_ask:always},reviewed_requirement_ids:cfg.requirements.map(r=>r.requirement_id)}});expect(confirmed.statusCode,confirmed.body).toBe(200);const created=await app.inject({method:'POST',url:'/api/simulations',headers:{'idempotency-key':'run00001'},payload:{config_id:cfg.config_id}});expect(created.statusCode,created.body).toBe(201);const run=created.json<SimRun>();return {app,run,m,headers,advance:(ms:number)=>{now=new Date(now.getTime()+ms);}};}
async function next(x:Awaited<ReturnType<typeof setup>>){const response=await x.app.inject({method:'POST',url:`/api/simulations/${x.run.run_id}/next`,headers:{'idempotency-key':'next0001'},payload:{}});expect(response.statusCode,response.body).toBe(200);return response.json<{run:SimRun;assessment:Assessment}>();}
it('commits ordinary simulation and repeats exact lost response without second purchase',async()=>{const x=await setup();const a=await next(x),b=await next(x);expect(a.assessment.decision).toBe('approve');expect(a.assessment.results).toHaveLength(50);expect(b).toEqual(a);expect(b.run.commitments).toHaveLength(1);expect(b.run.purchases).toHaveLength(1);});
it('exports a complete confirmed binding for the live engine',async()=>{const x=await setup();const response=await x.app.inject(`/api/safety-configs/${x.run.config.config_id}/export`);expect(response.statusCode,response.body).toBe(200);const exported=response.json();expect(exported.live_mandate_id).toBe(null);const pack=await loadDataPack({dataDir:resolve('data')});expect(()=>validateLiveBinding({...exported,live_mandate_id:'LIVE_MANDATE'},pack)).not.toThrow();});
it('resolves a typed human risk question and consumes consent once',async()=>{const x=await setup(true);const a=(await next(x)).assessment;expect(a.decision).toBe('step_up');const q=a.questions.find(q=>q.filter_ids.includes('C24'))!;expect(q.kind).toBe('confirm_risk');const request={method:'POST' as const,url:`/api/simulations/${x.run.run_id}/authorizations/${a.authorization_id}/human-responses`,headers:{...x.headers,'idempotency-key':'answer001'},payload:{expected_revision:a.revision,offer_hash:a.offer_hash,question_id:q.question_id,value:'confirm'}};const r=await x.app.inject(request);expect(r.statusCode,r.body).toBe(200);const result=r.json<{run:SimRun;assessment:Assessment}>();expect(result.assessment.decision).toBe('approve');expect(result.run.commitments).toHaveLength(1);expect(result.run.reservations).toHaveLength(0);expect(result.run.purchases[0]!.answers[0]!.consumed_by).toBe(result.assessment.assessment_id);expect((await x.app.inject(request)).json()).toEqual(result);});
it('forged browser actor cannot answer through an agent channel',async()=>{const x=await setup(true);const a=(await next(x)).assessment;const r=await x.app.inject({method:'POST',url:`/api/simulations/${x.run.run_id}/authorizations/${a.authorization_id}/human-responses`,headers:{'idempotency-key':'forged001'},payload:{expected_revision:a.revision,offer_hash:a.offer_hash,question_id:a.questions[0]!.question_id,value:'confirm'}});expect(r.statusCode).toBe(403);expect(r.json().error.code).toBe('G03_HUMAN_CHANNEL_REQUIRED');});
it('revocation between question and click preserves zero spending',async()=>{const x=await setup(true);const a=(await next(x)).assessment;const revoked=await x.app.inject({method:'DELETE',url:`/api/mandates/${x.m.mandate_id}`,headers:{'idempotency-key':'revoke001'}});expect(revoked.statusCode,revoked.body).toBe(200);const r=await x.app.inject({method:'POST',url:`/api/simulations/${x.run.run_id}/authorizations/${a.authorization_id}/human-responses`,headers:{...x.headers,'idempotency-key':'answer001'},payload:{expected_revision:a.revision,offer_hash:a.offer_hash,question_id:a.questions[0]!.question_id,value:'confirm'}});expect(r.statusCode).toBe(409);const run=(await x.app.inject(`/api/simulations/${x.run.run_id}`)).json<SimRun>();expect(run.commitments).toHaveLength(0);expect(run.reservations).toHaveLength(0);expect(run.purchases[0]!.assessments.at(-1)?.blocking_filter_ids).toContain('C02');});
it('a negative human response cancels and releases without marking a business denial',async()=>{const x=await setup(true);const a=(await next(x)).assessment;const r=await x.app.inject({method:'POST',url:`/api/simulations/${x.run.run_id}/authorizations/${a.authorization_id}/cancel`,headers:{...x.headers,'idempotency-key':'cancel001'},payload:{}});expect(r.statusCode).toBe(200);const run=r.json<SimRun>();expect(run.purchases[0]!.assessments.at(-1)?.execution_state).toBe('cancelled');expect(run.commitments).toHaveLength(0);expect(run.reservations).toHaveLength(0);});

it('expires the human reservation durably before rejecting a late answer',async()=>{const x=await setup(true);const a=(await next(x)).assessment;x.advance(120000);const response=await x.app.inject({method:'POST',url:`/api/simulations/${x.run.run_id}/authorizations/${a.authorization_id}/human-responses`,headers:{...x.headers,'idempotency-key':'late00001'},payload:{expected_revision:a.revision,offer_hash:a.offer_hash,question_id:a.questions[0]!.question_id,value:'confirm'}});expect(response.statusCode).toBe(409);expect(response.json().error.code).toBe('G04_CONFIRMATION_EXPIRED');const current=(await x.app.inject(`/api/simulations/${x.run.run_id}`)).json<SimRun>();expect(current.reservations).toHaveLength(0);expect(current.commitments).toHaveLength(0);expect(current.purchases[0]!.assessments.at(-1)?.execution_state).toBe('expired');expect(current.audit.some(e=>e.event==='expired')).toBe(true);});

it('re-evaluates an expired purchase at its latest revision without reusing old consent or duplicating reservations',async()=>{
 const x=await setup(true),initial=(await next(x)).assessment;x.advance(120001);
 const expired=(await x.app.inject(`/api/simulations/${x.run.run_id}`)).json<SimRun>().purchases[0]!.assessments.at(-1)!;
 expect(expired.execution_state).toBe('expired');expect(expired.revision).toBeGreaterThan(initial.revision);
 const request={method:'POST' as const,url:`/api/simulations/${x.run.run_id}/authorizations/${initial.authorization_id}/reassess`,headers:{...x.headers,'idempotency-key':'reassess1'},payload:{expected_revision:expired.revision}};
 const reply=await x.app.inject(request);expect(reply.statusCode,reply.body).toBe(200);
 const result=reply.json<{run:SimRun;assessment:Assessment}>();
 expect(result.assessment.execution_state).toBe('awaiting_user');expect(result.assessment.lock?.expires_at).not.toBe(initial.lock?.expires_at);expect(result.run.commitments).toHaveLength(0);expect(result.run.reservations).toHaveLength(1);
 expect((await x.app.inject(request)).json()).toEqual(result);
 const stale=await x.app.inject({method:'POST',url:`/api/simulations/${x.run.run_id}/authorizations/${initial.authorization_id}/human-responses`,headers:{...x.headers,'idempotency-key':'old-answer'},payload:{expected_revision:initial.revision,offer_hash:initial.offer_hash,question_id:initial.questions[0]!.question_id,value:'confirm'}});
 expect(stale.statusCode).toBe(409);expect(stale.json().error.code).toBe('G05_REVISION_CONFLICT');
});
