import { mkdtemp } from "node:fs/promises";
import { join } from "node:path";
import { tmpdir } from "node:os";
import { describe, expect, it } from "vitest";
import { fixture } from "./simulation-fixture.js";
import { VisecaClient } from "../packages/local-runtime/src/simulation/viseca-client.js";
import { VisecaOutbox, VisecaWorker } from "../packages/local-runtime/src/simulation/viseca-worker.js";

const event = () => ({ ...fixture().event, deadline_at: "2026-09-19T00:00:08.000Z" });
async function setup(handler: (path: string, init?: RequestInit) => Promise<Response>, now = Date.parse("2026-09-19T00:00:00.000Z")) { const dir = await mkdtemp(join(tmpdir(), "viseca-live-")); const outbox = new VisecaOutbox(join(dir, "outbox.sqlite")); await outbox.load(); const worker = new VisecaWorker(new VisecaClient("http://fake", undefined, handler), outbox, () => now, 100); await worker.startRun("LIVE_RUN", {}); return { worker, outbox }; }
const json = (value: unknown, status = 200) => new Response(JSON.stringify(value), { status, headers: { "content-type": "application/json" } });

describe("live worker", () => {
  it("treats 204 as a non-terminal poll", async () => { const { worker: w } = await setup(async () => new Response(null, { status: 204 })); expect(await w.pollOnce(async () => ({ decision: "approve" }))).toBeNull(); });
  it("accepts an approval", async () => { let posts = 0; const { worker: w } = await setup(async (p) => p.includes("/authorizations/") ? (++posts, json({ status: "approved", decision: "approve" })) : json({ run_id: "LIVE_RUN", data: event() })); const r = await w.pollOnce(async () => ({ decision: "approve" })); expect(r?.state).toBe("accepted"); expect(posts).toBe(1); });
  it("turns evaluator failure into step_up", async () => { const { worker: w } = await setup(async (p) => p.includes("/authorizations/") ? json({ status: "accepted", decision: "step_up" }) : json({ run_id: "LIVE_RUN", data: event() })); const r = await w.pollOnce(async () => { throw new Error("engine"); }); expect(r?.decision).toBe("step_up"); });
  it("does not post a duplicate authorization", async () => { let posts = 0; const e = event(); const { worker: w } = await setup(async (p) => p.includes("/authorizations/") ? (++posts, json({ status: "approved", decision: "approve" })) : json({ run_id: "LIVE_RUN", data: e })); await w.pollOnce(async () => ({ decision: "approve" })); await w.pollOnce(async () => ({ decision: "approve" })); expect(posts).toBe(1); });
  it("reconciles a lost approval response", async () => { let first = true; const e = event(); const { worker: w } = await setup(async (p) => { if (p.includes("decision-requests")) return json({ run_id: "LIVE_RUN", data: e });
 if (p.includes("/authorizations/") && first) { first = false; throw new Error("lost"); } return p.includes("events") ? json({ data: [{ run_id: "LIVE_RUN", authorization_id: e.authorization.authorization_id, status: "approved", decision: "approve" }] }) : json({ data: [] }); }); const r = await w.pollOnce(async () => ({ decision: "approve" })); expect(r?.state).toBe("submission_unknown"); expect((await w.reconcile()).accepted).toContain(e.authorization.authorization_id); });
  it("rejects ambiguous accepted status", async () => { const e = event(); const { worker: w } = await setup(async (p) => p.includes("events") ? json({ data: [{ run_id: "LIVE_RUN", authorization_id: e.authorization.authorization_id, status: "accepted" }] }) : json({ run_id: "LIVE_RUN", data: e })); await w.pollOnce(async () => ({ decision: "approve" })); expect((await w.reconcile()).accepted).toEqual([]); });
  it("requires the authenticated human callback", async () => { const { worker: w } = await setup(async (p) => p.includes("/authorizations/") ? json({ status: "accepted", decision: "step_up" }) : json({ run_id: "LIVE_RUN", data: event() })); const r = await w.pollOnce(async () => ({ decision: "step_up" })); await expect(w.resolve(r!.id, "approve", "forged", async () => { throw new Error("denied"); }, async () => true)).rejects.toThrow("denied"); });
  it("keeps the run snapshot immutable", async () => { const { worker: w } = await setup(async () => new Response(null, { status: 204 })); await expect(w.startRun("LIVE_RUN", { changed: true })).rejects.toThrow("immutable_live_snapshot_conflict"); });
  it("does not POST when the deadline has already passed", async () => { let posts = 0; const { worker: w } = await setup(async (p) => { if (p.includes("/authorizations/")) posts++; return json({ run_id: "LIVE_RUN", data: event() }); }, Date.parse("2026-09-19T00:00:09.000Z")); const r = await w.pollOnce(async () => ({ decision: "approve" })); expect(r?.state).toBe("deadline_missed"); expect(posts).toBe(0); });
  it("bounds a slow evaluator and sends step_up before the deadline", async () => { let posts = 0; const { worker: w } = await setup(async (p) => p.includes("/authorizations/") ? (++posts, json({ status: "accepted", decision: "step_up" })) : json({ run_id: "LIVE_RUN", data: event() }), Date.parse("2026-09-19T00:00:07.500Z")); const r = await w.pollOnce(async () => { await new Promise((resolve) => setTimeout(resolve, 500)); return { decision: "approve" }; }); expect(r?.decision).toBe("step_up"); expect(posts).toBe(1); });
  it("retains resolve intent when the human submission response is lost", async () => { let resolveCall = false; const e = event(); const { worker: w, outbox } = await setup(async (p) => { if (p.includes("decision-requests")) return json({ run_id: "LIVE_RUN", data: e }); if (p.includes("/decision")) return json({ status: "accepted", decision: "step_up" }); if (p.includes("/resolve")) { resolveCall = true; throw new Error("lost"); } return json({ data: [] }); }); const r = await w.pollOnce(async () => ({ decision: "step_up" })); expect(r?.state).toBe("awaiting_human"); await expect(w.resolve(r!.id, "approve", "session", async () => ({ actor_id: "server-user", proof: "server-proof" }), async () => true)).rejects.toThrow("human_submission_unknown"); expect(resolveCall).toBe(true); const saved = outbox.value.entries.find((entry) => entry.id === r!.id)!; expect(saved.intent?.operation).toBe("resolve"); expect(saved.intent?.decision).toBe("approve"); expect(saved.reserved).toBe(true); });
});
