import {configuredInstructionDecoder,readyWalletPreparation} from './helpers/configured-instruction-decoder.js';
import {DatabaseSync} from 'node:sqlite';
import {mkdtemp,rm} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join,resolve} from 'node:path';
import {afterEach,it,expect} from 'vitest';
import type {FastifyInstance} from 'fastify';
import {createLocalApp} from '../apps/local-web/src/app.js';
import type {WalletPreparation,WalletRunView} from '../packages/contracts/src/wallet.js';
const resources:Array<{app:FastifyInstance;dir:string}>=[];
afterEach(async()=>{for(const r of resources.splice(0)){await r.app.close();await rm(r.dir,{recursive:true,force:true});}});
async function setup(scenario_id='SCEN0001'){
 const dir=await mkdtemp(join(tmpdir(),'wallet-flow-'));const app=await createLocalApp({stateDir:join(dir,'state'),outputDir:join(dir,'output'),webDir:resolve('apps/local-web/web'),instructionDecoder:configuredInstructionDecoder()});resources.push({app,dir});
 const options=(await app.inject('/api/wallet/options')).json();const scenario=options.scenarios.find((s:{scenario_id:string})=>s.scenario_id===scenario_id);const session=await app.inject(`/api/wallet/session?scenario_id=${scenario_id}`);const headers={cookie:String(session.headers['set-cookie']).split(';')[0]!,'x-csrf-token':session.json().csrf,'idempotency-key':'prepare-request-001'};
 const prepared=await app.inject({method:'POST',url:'/api/wallet/prepare',headers,payload:{scenario_id,instruction:scenario.instruction,mode:'local'}});expect(prepared.statusCode,prepared.body).toBe(202);const prep=await readyWalletPreparation(async()=>(await app.inject(`/api/wallet/preparations/${prepared.json().preparation_id}`)).json<WalletPreparation>());expect(prep.status).toBe('ready');return {app,headers,prep,scenario};
}
async function confirm(x:Awaited<ReturnType<typeof setup>>,edits:Record<string,unknown>={}){return x.app.inject({method:'POST',url:`/api/wallet/preparations/${x.prep.preparation_id}/confirm`,headers:{...x.headers,'idempotency-key':'confirm-request-001'},payload:{confirmed:true,parameters:{...x.prep.config!.parameters,...edits}}});}
it('one explicit confirmation creates one mandate/run and starts automatic evaluation',async()=>{const x=await setup();expect(x.prep.permissions.some(p=>p.key==='allowed_currencies'&&p.value==='Any supported currency')).toBe(true);const response=await confirm(x);expect(response.statusCode,response.body).toBe(200);const result=response.json();expect((await confirm(x)).json()).toEqual(result);await new Promise(r=>setTimeout(r,1900));const run=(await x.app.inject(`/api/wallet/runs/${result.run_id}`)).json<WalletRunView>();expect(run.purchases).toHaveLength(1);expect(run.purchases[0]!.assessment?.decision).toBe('approve');expect(run.approved_chf).toBe('44.50');expect(run.config.parameters.max_order_chf).toBe('120');expect(run.config.parameters.allowed_currencies).toBe(null);});
it('requires server customer session and an explicit confirmation',async()=>{const x=await setup();const response=await x.app.inject({method:'POST',url:`/api/wallet/preparations/${x.prep.preparation_id}/confirm`,headers:{'idempotency-key':'no-human-session'},payload:{confirmed:true,parameters:{}}});expect(response.statusCode).toBe(403);const no=await x.app.inject({method:'POST',url:`/api/wallet/preparations/${x.prep.preparation_id}/confirm`,headers:x.headers,payload:{confirmed:false,parameters:{}}});expect(no.statusCode).toBe(422);expect((await x.app.inject('/api/wallet/runs')).json().runs).toHaveLength(0);});
it('prepares complete shoe parameters without a separate size question',async()=>{const x=await setup('SCEN0002');expect(x.prep.clarifications).toEqual([]);expect(x.prep.config!.parameters.numeric_size_convention).toBe('shared_numeric');const response=await confirm(x);expect(response.statusCode,response.body).toBe(200);});
it('resolves the unambiguous 27-inch catalogue monitor into the executable JSON',async()=>{const x=await setup('SCEN0004');expect(x.prep.clarifications).toEqual([]);expect(x.prep.config!.parameters.allowed_item_ids).toEqual(['IT0017']);const response=await confirm(x);expect(response.statusCode,response.body).toBe(200);});
it('supports a custom local instruction and rejects hosted mode without access',async()=>{const x=await setup();const response=await x.app.inject({method:'POST',url:'/api/wallet/prepare',headers:{...x.headers,'idempotency-key':'custom-instruction'},payload:{scenario_id:x.scenario.scenario_id,instruction:'Buy groceries for CHF 50 or less. Ask me when uncertain.',mode:'local'}});const prep=await readyWalletPreparation(async()=>(await x.app.inject(`/api/wallet/preparations/${response.json().preparation_id}`)).json<WalletPreparation>());expect(prep.instruction).toContain('CHF 50');x.prep=prep;expect((await confirm(x)).statusCode).toBe(200);});
it('revokes the mandate without losing approved history',async()=>{const x=await setup();const started=(await confirm(x)).json();await new Promise(r=>setTimeout(r,1900));const revoke=await x.app.inject({method:'POST',url:`/api/wallet/runs/${started.run_id}/revoke`,headers:{...x.headers,'idempotency-key':'revoke-wallet-001'},payload:{}});expect(revoke.statusCode,revoke.body).toBe(200);expect(revoke.json()).toMatchObject({status:'revoked',approved_chf:'44.50',reservations:0});});
it('does not interpret someone in a session warning as a one-item quantity limit',async()=>{const x=await setup('SCEN0003');expect(x.prep.config?.parameters.max_quantity_per_order).toBeNull();expect(x.prep.config?.parameters.watch_devices).toBe(true);});
it('allows a lower purchase limit at review and rejects widening it',async()=>{const x=await setup();const wider=await confirm(x,{max_order_chf:'121'});expect(wider.statusCode).toBe(409);const lower=await confirm(x,{max_order_chf:'40.50'});expect(lower.statusCode,lower.body).toBe(200);const run=(await x.app.inject(`/api/wallet/runs/${lower.json().run_id}`)).json<WalletRunView>();expect(run.config.parameters.max_order_chf).toBe('40.50');});

it('freezes only the customer history while retaining purchases on every customer card',async()=>{const x=await setup('SCEN0004');const response=await confirm(x);expect(response.statusCode,response.body).toBe(200);const db=new DatabaseSync(join(resources.at(-1)!.dir,'state','simulations.sqlite'),{readOnly:true});const state=JSON.parse(String(db.prepare('SELECT body FROM state').get()!['body']));db.close();const run=state.runs[0];expect(run.history.length).toBeGreaterThan(0);expect(run.history.every((h:{customer_id:string})=>h.customer_id===run.customer_id)).toBe(true);expect(new Set(run.history.map((h:{card_id:string})=>h.card_id)).size).toBeGreaterThan(1);expect(run.history_coverage.rows).toBe(run.history.length);});

it('rejects incomplete or unknown JSON parameters before creating a run',async()=>{const x=await setup();const unknown=await confirm(x,{made_up_rule:true});expect(unknown.statusCode).toBe(400);const incomplete=await x.app.inject({method:'POST',url:`/api/wallet/preparations/${x.prep.preparation_id}/confirm`,headers:x.headers,payload:{confirmed:true,parameters:{min_order_chf:null,max_order_chf:'120'}}});expect(incomplete.statusCode).toBe(400);expect((await x.app.inject('/api/wallet/runs')).json().runs).toEqual([]);});
it('executes exactly the equal lower and upper bounds submitted as JSON',async()=>{const x=await setup('SCEN0000');const response=await confirm(x,{min_order_chf:'20.00',max_order_chf:'20.00'});expect(response.statusCode,response.body).toBe(200);await new Promise(r=>setTimeout(r,1900));const view=(await x.app.inject(`/api/wallet/runs/${response.json().run_id}`)).json<WalletRunView>();expect(view.config.parameters).toMatchObject({min_order_chf:'20.00',max_order_chf:'20.00'});expect(view.purchases[0]!.assessment?.decision).toBe('approve');});
