import { Decimal } from 'decimal.js';
import { customerHistory, hash, na, pass, result, type EvaluationContext } from './common.js';
import type { Commitment, FilterId, FilterResult, Reservation } from '../../../contracts/src/simulation.js';
import { parseAttributes } from './parsers.js';
const sum=(values:Array<{amount_chf:string}>)=>values.reduce((n,c)=>n.plus(c.amount_chf),new Decimal(0));
function civil(timestamp:string,timezone:string):string {const parts=new Intl.DateTimeFormat('en-CA',{timeZone:timezone,year:'numeric',month:'2-digit',day:'2-digit'}).formatToParts(new Date(timestamp));return ['year','month','day'].map(t=>parts.find(p=>p.type===t)!.value).join('-');}
function hour(timestamp:string,timezone:string):number{return Number(new Intl.DateTimeFormat('en-GB',{timeZone:timezone,hour:'2-digit',hourCycle:'h23'}).format(new Date(timestamp)));}
function quantile(sorted:Decimal[],p:number):Decimal{const index=(sorted.length-1)*p;const lo=Math.floor(index),hi=Math.ceil(index);return sorted[lo]!.plus(sorted[hi]!.minus(sorted[lo]!).mul(String(index-lo)));}
export function affectedRolling(candidate:Commitment,entries:Commitment[],days:number):Array<{end:string;spent:string}> {
 const t=Date.parse(candidate.timestamp),duration=days*86400000;
 const ends=[candidate.timestamp,...entries.filter(c=>Date.parse(c.timestamp)>=t&&Date.parse(c.timestamp)<t+duration).map(c=>c.timestamp)];
 return [...new Set(ends)].map(end=>{const T=Date.parse(end);return {end,spent:sum([...entries,candidate].filter(c=>Date.parse(c.timestamp)>T-duration&&Date.parse(c.timestamp)<=T)).toFixed(2)};});
}
export function evaluateCustomer(ctx:EvaluationContext,merchantResults:FilterResult[]=[]):FilterResult[]{
 const {pack,event:e,config,run}=ctx,a=e.authorization,p=config.parameters,h=customerHistory(ctx),out:FilterResult[]=[];
 const card=pack.cardsById.get(a.card_id),account=card?pack.accountsById.get(card.account_id):undefined,authority=pack.authoritiesById.get(run.authority_id as never),t=Date.parse(a.timestamp);
 const review=(id:FilterId,code:string,message:string,observed:unknown=null,expected:unknown=null,fact=id,kind:'confirm_risk'|'provide_evidence'|'amend_mandate'='confirm_risk')=>result(id,'needs_review',code,message,observed,expected,{resolution:kind,fact_key:fact});
 const unavailable=(id:FilterId,message:string)=>result(id,'not_evaluated',`${id}_PREREQUISITE_UNAVAILABLE`,message,null,null,{depends_on:['M19']});
 const identityOk=account?.customer_id===e.mandate.customer_id&&e.mandate.customer_id===run.customer_id&&a.card_id===e.mandate.card_id&&a.card_id===run.card_id&&a.profile_id===e.mandate.profile_id&&a.mandate_id===e.mandate.mandate_id&&(!authority||(authority.card_id===a.card_id&&authority.customer_id===e.mandate.customer_id));
 out.push(!card||!account?result('C01','not_evaluated','C01_IDENTITY_DATA_UNAVAILABLE','Jointure carte, compte et client unavailable.'):identityOk?pass('C01','Propriété et identités exactes verifiedes.',{card:a.card_id,customer:account.customer_id,profile:a.profile_id}):result('C01','fail','C01_OWNER_MISMATCH','Les identités fiables du client, de la carte ou du mandat diffèrent.',{card:a.card_id,customer:account.customer_id},e.mandate));
 out.push(run.status==='revoked'||e.mandate.status!=='active'||a.authority_status!=='active'||(authority&&(t<Date.parse(authority.valid_from)||t>Date.parse(authority.valid_until)))?result('C02','fail','C02_MANDATE_INACTIVE','Mandate revoked, inactif ou outside période de validité.',{status:run.status,timestamp:a.timestamp},authority):!authority?result('C02','not_evaluated','C02_AUTHORITY_UNAVAILABLE','Autorité de référence unavailable.'):pass('C02','Mandate actif au temps simulé.'));
 const confirmedCoverage=config.status==='confirmed'&&config.instruction_hash===hash(config.instruction)&&config.requirements.length>0&&config.requirements.every(r=>r.status==='confirmed');
 const manualRequirements=p.manual_review_requirements??[];
 out.push(!confirmedCoverage?review('C03','C03_REQUIREMENT_UNRESOLVED','La couverture de l’instruction reste à confirmer.',null,null,'C03','amend_mandate'):manualRequirements.length?result('C03','needs_review','C03_PURCHASE_REQUIREMENTS_REVIEW','Verify the instruction against this purchase.',null,manualRequirements,{resolution:'confirm_requirement',fact_key:`manual_requirements:${hash(manualRequirements)}`,source_type:'mandate',source_ref:config.config_id,field:'manual_review_requirements'}):pass('C03','Couverture des requirements explicitement revue.'));
 const date=a.timestamp.slice(0,10);
 out.push(!card||!account?result('C04','not_evaluated','C04_REFERENCE_UNAVAILABLE','Référentiel carte unavailable.'):a.card_status_at_attempt==='blocked'||date>=card.expires_on?result('C04','fail','C04_CARD_UNAVAILABLE','Card bloquée à la tentative ou date d’expiration atteinte.',{status:a.card_status_at_attempt,date,expires_on:card.expires_on}):card.status!=='active'||account.status!=='active'||date<account.opened_on?result('C04','not_evaluated','C04_CARD_STATUS_UNCLEAR','The card and account reference status must be refreshed before payment.',{attempt:a.card_status_at_attempt,snapshot:card.status,account:account.status},null,{resolution:'retry_or_repair'}):pass('C04','Card active à la tentative ; expiration non atteinte.'));
 out.push(a.channel!=='ecommerce'?na('C05'):card?.online_enabled===false?result('C05','fail','C05_ONLINE_DISABLED','Payments en ligne désactivés.'):card?.online_enabled===true?pass('C05'):result('C05','not_evaluated','C05_ONLINE_CAPABILITY_UNKNOWN','The card issuer must confirm online payment capability.',null,null,{resolution:'retry_or_repair'}));
 out.push(card?.international_enabled===true?pass('C06','Capacité internationale active.'):p.domestic_country===null||!a.merchant.merchant_country?review('C06','C06_DOMESTIC_COUNTRY_UNCONFIRMED','Convention domestique requirede pour vérifier la capacité internationale.',null,null,'C06','amend_mandate'):a.merchant.merchant_country===p.domestic_country?pass('C06','Marchand domestique selon la convention confirmée.'):card?.international_enabled===false?result('C06','fail','C06_INTERNATIONAL_DISABLED','Ce paiement international est incompatible avec la carte.',a.merchant.merchant_country,p.domestic_country):result('C06','not_evaluated','C06_CAPABILITY_UNKNOWN','The card issuer must confirm international payment capability.',null,null,{resolution:'retry_or_repair'}));
 out.push(p.account_purpose===null?na('C08'):account?.account_purpose===p.account_purpose?pass('C08'):review('C08','C08_ACCOUNT_PURPOSE_CONFIRMATION_REQUIRED','Voulez-vous utiliser ce compte pour cet usage ?',account?.account_purpose,p.account_purpose));
 const amountResult=merchantResults.find(r=>r.filter_id==='M19');const reliable=amountResult?.outcome==='pass';const total=new Decimal(String(a.billing_amount_chf));
 const commitments=run.commitments.filter(c=>c.budget_scope_id===run.budget_scope_id&&c.authorization_id!==a.authorization_id);
 const reservations=run.reservations.filter(c=>c.budget_scope_id===run.budget_scope_id&&c.authorization_id!==a.authorization_id&&Date.parse(c.expires_at)>Date.parse(ctx.now));
 const quantity=a.items.reduce((n,i)=>n+i.quantity,0);const candidate:Commitment={authorization_id:a.authorization_id,amount_chf:total.toFixed(2),timestamp:a.timestamp,quantity,budget_scope_id:run.budget_scope_id};
 const caps=[p.max_order_chf,account?.per_transaction_limit_chf??null].filter((v):v is string=>v!==null);
 if(!reliable)out.push(unavailable('C09','The verified total is required before comparing amount bounds.'));
 else {
  const failed=caps.filter(limit=>total.gt(limit));
  out.push(p.min_order_chf!=null&&total.lt(p.min_order_chf)
   ?result('C09','fail','C09_PURCHASE_BELOW_MINIMUM','The total is below the confirmed minimum.',total.toFixed(2),p.min_order_chf)
   :failed.length?result('C09','fail','C09_PURCHASE_LIMIT_EXCEEDED','The total exceeds an applicable maximum.',total.toFixed(2),failed)
   :pass('C09','The total is within all confirmed amount bounds.',total.toFixed(2),{min_order_chf:p.min_order_chf??null,maxima_chf:caps}));
 }
 // Currency restrictions are explicit mandate requirements, independent from a CHF ceiling.
 if(p.allowed_currencies!==null&&!p.allowed_currencies.includes(a.currency)){const r=out.find(r=>r.filter_id==='C09')!;const fx=result('C09','fail','C09_TRANSACTION_CURRENCY_FORBIDDEN','La devise de paiement est explicitement exclue.',a.currency,p.allowed_currencies);r.outcome='fail';r.reasons.push(...fx.reasons);r.evidence.push(...fx.evidence);}
 const windows=p.rolling_budget?affectedRolling(candidate,commitments,p.rolling_budget.days):[];
 out.push(!p.rolling_budget?na('C10'):!reliable?unavailable('C10','Budget glissant suspendu tant que le montant manque.'):windows.some(w=>new Decimal(w.spent).gt(p.rolling_budget!.limit_chf))?result('C10','fail','C10_ROLLING_BUDGET_EXCEEDED','Une fenêtre glissante affectée exceedsrait le plafond.',windows,p.rolling_budget):pass('C10','Toutes les fenêtres affectées respectent le plafond.',windows,p.rolling_budget));
 const key=civil(a.timestamp,p.timezone);const calendar:Array<{period:string;limit:string;spent:string}>=[];
 for(const [period,limit,length] of [['day',p.daily_budget_chf,10],['month',p.monthly_budget_chf,7]] as const)if(limit!==null)calendar.push({period,limit,spent:sum([...commitments,candidate].filter(c=>civil(c.timestamp,p.timezone).slice(0,length)===key.slice(0,length))).toFixed(2)});
 out.push(!calendar.length?na('C11','Pas de budget civil local activé ; consommation bancaire globale non fournie.'):!reliable?unavailable('C11','Budget civil suspendu tant que le montant manque.'):calendar.some(w=>new Decimal(w.spent).gt(w.limit))?result('C11','fail','C11_CALENDAR_BUDGET_EXCEEDED','Budget civil local dépassé.',calendar):pass('C11','Budgets civils locaux respectés.',calendar));
 const reservationConflicts:unknown[]=[];
 if(p.rolling_budget){const combined=affectedRolling(candidate,[...commitments,...reservations],p.rolling_budget.days);if(combined.some(w=>new Decimal(w.spent).gt(p.rolling_budget!.limit_chf)))reservationConflicts.push({rolling:combined});}
 for(const [period,limit,length] of [['day',p.daily_budget_chf,10],['month',p.monthly_budget_chf,7]] as const)if(limit!==null){const spent=sum([...commitments,...reservations,candidate].filter(c=>civil(c.timestamp,p.timezone).slice(0,length)===key.slice(0,length)));if(spent.gt(limit))reservationConflicts.push({period,spent:spent.toFixed(2),limit});}
 if(p.mission_quantity!==null&&[...commitments,...reservations].reduce((n,c)=>n+c.quantity,quantity)>p.mission_quantity)reservationConflicts.push({quantity:true});
 // Capacity belongs to the transaction ledger. Customer testimony cannot free
 // it: wait for the other reservation to resolve, then recheck atomically.
 out.push(!reliable?unavailable('C12','No reservation without a reliable amount.'):reservations.length&&reservationConflicts.length?result('C12','not_evaluated','C12_BUDGET_RESERVED_ELSEWHERE','Other pending purchases reserve the required capacity. Retry after a reservation is released.',reservationConflicts,null,{resolution:'retry_or_repair',source_type:'ledger',source_ref:run.run_id,fact_key:'C12'}):pass('C12','Capacité de réservation disponible ; les réservations ne sont pas des dépenses.',reservations.map(r=>r.authorization_id)));
 const signature=(items:typeof a.items)=>hash(items.map(i=>[i.item_id,i.quantity,parseAttributes(i.item_details).filter(v=>v.selected&&!v.negated).map(v=>[v.attribute,v.value,v.unit]).sort()]).sort((x,y)=>String(x[0]).localeCompare(String(y[0]))));
 const dup=run.purchases.filter(purchase=>{const pa=purchase.event.authorization,s=purchase.assessments.at(-1);return pa.authorization_id!==a.authorization_id&&pa.merchant.merchant_id===a.merchant.merchant_id&&Date.parse(pa.timestamp)<=t&&t-Date.parse(pa.timestamp)<= (p.duplicate_hours??0)*3600000&&['approved','awaiting_user','technical_hold'].includes(s?.execution_state??'')&&signature(pa.items)===signature(a.items);});
 out.push(p.duplicate_hours===null?na('C13'):dup.length?review('C13','C13_POSSIBLE_DUPLICATE','Un achat similaire est déjà authorized ou en attente. Souhaitez-vous un exemplaire supplémentaire ?',dup.map(p=>p.event.authorization.authorization_id)):pass('C13','No achat runtime similaire dans cet horizon.'));
 const qty=commitments.reduce((n,c)=>n+c.quantity,0);out.push(p.mission_quantity===null?na('C14'):qty+quantity>p.mission_quantity?result('C14','fail','C14_MISSION_QUANTITY_EXCEEDED','La quantité de mission déjà authorizede et la demande exceedsnt le maximum.',{approved:qty,candidate:quantity},p.mission_quantity):pass('C14','Quantity de mission disponible.',{approved:qty,candidate:quantity},p.mission_quantity));
 const devices=new Set(h.map(h=>h.customer_device_id).filter(Boolean));out.push(!p.watch_devices?na('C15'):a.customer_device_id&&devices.has(a.customer_device_id)?pass('C15','Device observé dans l’historique client gelé.',a.customer_device_id):review('C15','C15_DEVICE_CONFIRMATION_REQUIRED','Cet appareil est absent de l’historique client. Êtes-vous à l’origine de l’achat ?',a.customer_device_id));
 const burst=run.purchases.filter(p=>p.event.authorization.authorization_id!==a.authorization_id&&Date.parse(p.event.authorization.timestamp)>=t-600000&&Date.parse(p.event.authorization.timestamp)<t).length;
 out.push(p.burst_threshold===null?na('C16'):burst>=p.burst_threshold?review('C16','C16_ATTEMPT_BURST',`${burst} tentatives antérieures en dix minutes ; confirmez cet achat.`,burst,p.burst_threshold):burst!==a.recent_attempt_count_10m?review('C16','C16_COUNTER_COVERAGE_MISMATCH','The counter source et le registre runtime diffèrent ; confirmez le contexte.',{source:a.recent_attempt_count_10m,runtime:burst}):pass('C16','Accountur runtime verified.',burst));
 const localHour=hour(a.timestamp,p.timezone),recent=h.filter(h=>Date.parse(h.timestamp)>=t-180*86400000);let unusualTime=false;
 if(p.time_review){const {from_hour:from,to_hour:to}=p.time_review;unusualTime=from<=to?localHour>=from&&localHour<to:localHour>=from||localHour<to;}
 if(p.historical_time_review&&recent.length>=20){const count=recent.filter(h=>Math.floor(hour(h.timestamp,p.timezone)/4)===Math.floor(localHour/4)).length;unusualTime ||=count<2&&count/recent.length<.05;}
 out.push(!p.time_review&&!p.historical_time_review?na('C18'):unusualTime?review('C18','C18_UNUSUAL_TIME',`Horaire ${localHour} h (${p.timezone}) à confirmer.`,{localHour,n:recent.length}):!p.time_review&&recent.length<20?na('C18','Signal unavailable : moins de 20 observations.'):pass('C18','Horaire sans signal selon le réglage.',localHour));
 const countries=new Set(h.map(h=>h.merchant_country));out.push(!p.unusual_country?na('C19'):h.length<20?na('C19','Signal unavailable : moins de 20 observations.'):countries.has(a.merchant.merchant_country)?pass('C19','Country marchand déjà observé.',a.merchant.merchant_country):review('C19','C19_COUNTRY_CONFIRMATION_REQUIRED','Country marchand absent de l’historique client.',a.merchant.merchant_country));
 const cohort=recent.filter(h=>h.merchant_category===a.merchant.merchant_category&&new Decimal(h.billing_amount_chf).gt(0)).map(h=>new Decimal(h.billing_amount_chf)).sort((a,b)=>a.cmp(b));
 if(!p.unusual_amount)out.push(na('C20'));else if(!reliable||cohort.length<20||new Set(a.items.map(i=>i.item_category)).size>1)out.push(na('C20','Cohorte comparable insuffisante ou montant unavailable.'));else {const med=quantile(cohort,.5),q1=quantile(cohort,.25),q3=quantile(cohort,.75),limit=Decimal.max(med.mul(3),q3.plus(q3.minus(q1).mul(3)));out.push(total.gt(limit)?review('C20','C20_UNUSUAL_AMOUNT','Amount inhabituel pour ces achats comparables.',{amount:total.toFixed(2),n:cohort.length,median:med.toFixed(2),threshold:limit.toFixed(2)}):pass('C20','Amount sans anomalie dans la cohorte comparable.',{n:cohort.length,threshold:limit.toFixed(2)}));}
 const preferenceMatches=a.items.filter(i=>p.preference_categories.includes(i.item_category));out.push(!p.preference_categories.length?na('C22'):preferenceMatches.length?review('C22','C22_PREFERENCE_CONFIRMATION_REQUIRED','Ce panier s’écarte d’une preference revue. Voulez-vous le conserver ?',preferenceMatches.map(i=>i.item_category),p.preference_categories):pass('C22','No écart à la preference activée.'));
 out.push(p.always_ask||(reliable&&p.autonomous_limit_chf!==null&&total.gt(p.autonomous_limit_chf))?review('C24','C24_HUMAN_APPROVAL_REQUIRED','Votre réglage d’autonomie demande une confirmation pour cet achat.',total.toFixed(2),p.autonomous_limit_chf):pass('C24','Noe confirmation systématique supplémentaire requirede.'));
 out.push(pass('C25','Questions regroupées après tous les contrôles indépendants.'));const c26=na('C26','Identity d’agent non fournie par le pack : contrôle non couvert.');c26.coverage='unavailable';out.push(c26);return out;
}
