import { Decimal } from 'decimal.js';
import type { EvaluationContext } from './common.js';
import { customerHistory, lastAssessment, na, pass, result, hash } from './common.js';
import { detectInjection, parseAttributes, parseReturnTerms, levenshtein } from './parsers.js';
import type { FilterResult } from '../../../contracts/src/simulation.js';

export function evaluateMerchant(ctx: EvaluationContext): FilterResult[] {
 const {event:e,config:c,pack}=ctx; const a=e.authorization; const m=a.merchant; const hist=customerHistory(ctx); const p=c.parameters; const out:FilterResult[]=[];
 const clientMerchantIds=new Set(hist.map(h=>h.merchant_id)); const known=pack.merchants.filter(x=>clientMerchantIds.has(x.merchant_id)&&x.merchant_id!==m.merchant_id&&x.merchant_name.length>=6&&m.merchant_name.length>=6&&levenshtein(x.merchant_name.normalize('NFKC').toLowerCase(),m.merchant_name.normalize('NFKC').toLowerCase())<=1);
 const canonical=pack.merchantsById.get(m.merchant_id);out.push(!canonical||canonical.merchant_name!==m.merchant_name||canonical.merchant_country!==m.merchant_country||canonical.merchant_category!==m.merchant_category||canonical.merchant_mcc!==m.merchant_mcc?result('M01','needs_review','M01_MERCHANT_IDENTITY_UNRESOLVED','Identity marchand absente ou contradictoire.',m,canonical??null):known.length?result('M01','needs_review','M01_MERCHANT_NAME_SIMILAR','Identity proche avec un identifiant différent.',m.merchant_name,known.map(x=>x.merchant_name)):pass('M01','Identity exacte resolved.',m.merchant_id));
 if(!p.familiar_merchant) out.push(na('M02')); else {const hs=hist.filter(h=>h.merchant_id===m.merchant_id);out.push(hs.length?pass('M02','Prior approved purchase observed.',hs.map(h=>h.authorization_id)):p.bounded_history_required?result('M02','fail','M02_CONFIRMED_HISTORY_RULE_NOT_MET','No purchase in the explicitly confirmed historical reference.',0,ctx.run.history_coverage):result('M02','needs_review','M02_FAMILIARITY_UNPROVEN','No prior approved purchase observed.',ctx.run.history_coverage,null,{resolution:'amend_mandate'}));}
 const allCards=hist.filter(h=>h.merchant_id===m.merchant_id); const same=allCards.filter(h=>h.card_id===a.card_id); out.push(allCards.length&&!same.length?result('M03','pass','M03_FAMILIARITY_FOUND_OTHER_CARD','Merchant connu via une autre carte.',allCards.map(h=>h.authorization_id)):pass('M03','Portée client/carte cohérente.',{same:same.length,all:allCards.length}));
 if(!p.regularity) out.push(na('M04')); else {const t=Date.parse(a.timestamp), from=t-p.regularity.days*86400000;const days=new Set(hist.filter(h=>h.merchant_id===m.merchant_id&&Date.parse(h.timestamp)>=from&&Date.parse(h.timestamp)<t).map(h=>new Intl.DateTimeFormat('en-CA',{timeZone:p.timezone,year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date(h.timestamp))));out.push(days.size>=p.regularity.distinct_dates?pass('M04','Régularité confirmée.',days.size,p.regularity.distinct_dates):result('M04',Date.parse(ctx.run.history_coverage.from)<=from&&Date.parse(ctx.run.history_coverage.to)>=t?'fail':'needs_review','M04_REGULARITY_BELOW_CONFIRMED_MINIMUM','The frequency observée est inférieure au seuil confirmé.',days.size,p.regularity.distinct_dates));}
 if(p.blocked_merchant_ids.includes(m.merchant_id)) out.push(result('M05','fail','M05_MERCHANT_EXPLICITLY_BLOCKED','Merchant explicitement interdit.',m.merchant_id)); else if(p.allowed_merchant_ids!==null&&!p.allowed_merchant_ids.includes(m.merchant_id)) out.push(result('M05','fail','M05_MERCHANT_OUTSIDE_ALLOWLIST','Merchant outside liste authorizede.',m.merchant_id)); else out.push(p.blocked_merchant_ids.length||p.allowed_merchant_ids!==null?pass('M05','Liste de vendeurs respectée.'):na('M05'));
 if(p.allowed_merchant_categories===null) out.push(na('M06')); else out.push(p.allowed_merchant_categories.includes(m.merchant_category)?pass('M06','Type de vendeur accepté.',m.merchant_category,p.allowed_merchant_categories):result('M06','fail','M06_MERCHANT_TYPE_MISMATCH','Type de vendeur incompatible.',m.merchant_category,p.allowed_merchant_categories));
 if(p.allowed_merchant_countries===null) out.push(na('M07')); else out.push(p.allowed_merchant_countries.includes(m.merchant_country)?pass('M07','Country authorized.',m.merchant_country):result('M07','fail','M07_MERCHANT_COUNTRY_OUTSIDE_ALLOWLIST','Country du vendeur non authorized.',m.merchant_country,p.allowed_merchant_countries));
 out.push(pass('M08','Canal et disponibilité conservés.',{channel:a.channel,availability:m.availability}));
 if(p.allowed_item_categories===null)out.push(na('M09'));else for(const item of a.items){const canonical=pack.itemsById.get(item.item_id as never);out.push(!canonical||canonical.item_category!==item.item_category?result('M09','needs_review','M09_ITEM_CATEGORY_UNRESOLVED','Catégorie structurée absente ou contradictoire.',item.item_category,canonical?.item_category,{fact_key:`category:${item.line_no}`}):p.allowed_item_categories.includes(canonical.item_category)?pass('M09','Catégorie de cette ligne acceptée.',canonical.item_category):result('M09','fail','M09_ITEM_CATEGORY_MISMATCH',`La ligne ${item.line_no} est outside catégorie authorizede.`,canonical.item_category,p.allowed_item_categories));}
 if(p.allowed_item_ids===null&&p.product_type===null)out.push(na('M10'));else for(const item of a.items){
  const known=pack.itemsById.get(item.item_id as never);const kind=(text:string):string|null=>/trail/i.test(text)?'trail':/road[- ]running|course sur route/i.test(text)?'road':/monitor|moniteur|screen/i.test(text)?'monitor':/helmet|casque/i.test(text)?'helmet':null;
  const expected=p.product_type?kind(p.product_type.replaceAll('_',' ')):null;const catalogKind=known?kind(known.item_name):null;const offerKind=kind(item.item_name+' '+item.item_details.split(/[.;]/).filter(s=>!detectInjection(s).detected).join(' '));
  out.push(p.allowed_item_ids!==null&&!p.allowed_item_ids.includes(item.item_id)?result('M10','fail','M10_PRODUCT_MISMATCH','Référence outside sélection confirmée.',item.item_id,p.allowed_item_ids):p.product_type!==null&&(!known||!expected||!catalogKind||(offerKind!==null&&offerKind!==catalogKind))?result('M10','needs_review','M10_PRODUCT_TYPE_UNRESOLVED','Type produit absent ou contradictoire entre catalogue et offre.',{catalogue:known?.item_name,offer:item.item_name,offerKind},p.product_type,{fact_key:`M10:${item.line_no}`}):expected&&catalogKind!==expected?result('M10','fail','M10_PRODUCT_MISMATCH','Type de produit certainement incompatible.',catalogKind,expected):pass('M10','Product identifié.',item.item_id,p.allowed_item_ids));
 }

 if(!p.attributes.length)out.push(na('M11'));else for(const item of a.items)for(const req of p.attributes){
   const fact_key=`M11:${req.name}:${item.line_no}`;let usedAnswer:EvaluationContext['answers'][number]|undefined;let text=item.item_details;let attrs=parseAttributes(text+' '+(req.name==='inches'?item.item_name:''));let vals=attrs.filter(v=>v.attribute===req.name);
   // A sourced observation supplements absence. A choice only selects an already
   // offered alternative; it cannot overwrite an explicit or certain variant.
   const answer=[...ctx.answers].reverse().find(a=>a.fact_key===fact_key&&a.source_ref&&a.source_excerpt);
   if(answer){
    const observed=parseAttributes(answer.source_excerpt!).filter(v=>v.attribute===req.name);
    const alternatives=vals.filter(v=>!v.negated);
    const unresolved=!vals.some(v=>v.selected)&&new Set(alternatives.map(v=>v.value)).size>1;
    const chosen=observed.filter(v=>!v.negated&&!v.ambiguous);
    const validChoice=answer.kind==='choose_variant'&&unresolved&&chosen.length===1&&observed.length===1&&answer.value.trim().toLowerCase()===chosen[0]!.value&&alternatives.some(v=>v.value===chosen[0]!.value&&(v.unit??p.numeric_size_convention)===(chosen[0]!.unit??p.numeric_size_convention));
    if(!vals.length||validChoice){usedAnswer=answer;text=answer.source_excerpt!;vals=observed;}
   }
   const contaminated=detectInjection(text).detected;const selected=vals.filter(v=>v.selected&&!v.negated);if(selected.length)vals=selected;
   const positive=vals.filter(v=>!v.negated);const units=positive.map(v=>v.unit??p.numeric_size_convention);const expectedUnit=req.unit??(req.name==='size'?p.numeric_size_convention:req.name==='inches'?'inch':null);
   const ambiguous=vals.some(v=>v.negated||v.ambiguous)||new Set(positive.map(v=>v.value)).size>1||(req.name==='size'&&(!expectedUnit||units.some(u=>u!==expectedUnit)))||(req.unit!==null&&positive.some(v=>v.unit!==req.unit));
   const mismatch=positive.length>0&&!ambiguous&&positive.every(v=>!req.values.includes(v.value));
   out.push(!vals.length?result('M11','needs_review','M11_ATTRIBUTE_MISSING',`La ${req.name} proposede est absente ; ${req.values.join(' ou ')} demandé.`,null,req,{fact_key}):ambiguous?result('M11','needs_review','M11_VARIANT_SELECTION_REQUIRED','Valeur, système ou variante non resolveds.',vals,req,{fact_key,resolution:'choose_variant'}):mismatch?result('M11','fail','M11_ATTRIBUTE_MISMATCH',`Attribut ${req.name} proposed ${positive.map(v=>v.value).join(', ')} au lieu de ${req.values.join(' ou ')}.`,vals,req,{fact_key}):contaminated?result('M11','needs_review','M11_ATTRIBUTE_CONFLICT','La preuve positive provient d’un champ contaminé ; vérifiez le fait.',vals,req,{fact_key}):pass('M11',`Attribut ${req.name} verified.`,vals,req));
  const evaluated=out.at(-1)!;for(const reason of evaluated.reasons)reason.fact_key=fact_key;for(const evidence of evaluated.evidence){evidence.source_type=usedAnswer?'human_review':'parser';evidence.source_ref=usedAnswer?.source_ref??`${e.request_id}:line:${item.line_no}`;evidence.excerpt=text;evidence.source_hash=hash(text);evidence.field=`authorization.items[${item.line_no}].item_details`;evidence.author=usedAnswer?.actor.actor_id??null;}
 }
 if(!p.no_extras&&p.max_quantity_per_order===null&&p.allowed_item_ids===null) out.push(na('M12')); else {const q=a.items.reduce((n,i)=>n+i.quantity,0);const extra=p.no_extras&&p.allowed_item_ids!==null&&a.items.some(i=>!p.allowed_item_ids!.includes(i.item_id));out.push(p.no_extras&&p.allowed_item_ids===null?result('M12','needs_review','M12_SELECTION_REQUIRED','The selection exacte est nécessaire pour vérifier les suppléments.',null,null,{resolution:'amend_mandate'}):extra?result('M12','fail','M12_UNAUTHORIZED_EXTRA','Ligne supplémentaire non authorizede.'):p.max_quantity_per_order!==null&&q>p.max_quantity_per_order?result('M12','fail','M12_QUANTITY_EXCEEDED','Quantity maximale dépassée.',q,p.max_quantity_per_order):pass('M12','Quantitys conformes.',q));}
 if(p.min_return_days===null)out.push(na('M13'));else for(const item of a.items){const fact_key=`M13:${item.line_no}`;let usedAnswer:EvaluationContext['answers'][number]|undefined;let text=item.item_details;let rt=parseReturnTerms(text);if(rt.days===undefined&&rt.returnable!==false){const answer=ctx.answers.find(a=>a.fact_key===fact_key&&a.source_ref&&a.source_excerpt);if(answer){usedAnswer=answer;text=answer.source_excerpt!;rt=parseReturnTerms(text);}}
 const structured=a.order_returnable;const conflict=rt.conflict||(structured==='false'&&rt.returnable===true)||(structured==='true'&&rt.returnable===false);
 out.push(conflict?result('M13','needs_review','M13_RETURN_TERMS_CONFLICT','Conditions de retour contradictoires.',{structured,rt},p.min_return_days,{fact_key}):structured==='false'||rt.returnable===false?result('M13','fail','M13_RETURNS_NOT_ALLOWED','Return certainement non authorized.',{structured,rt},p.min_return_days):rt.days===undefined?result('M13','needs_review','M13_RETURN_TERMS_UNCLEAR','Durée de retour unknown sur cette ligne.',null,p.min_return_days,{fact_key}):rt.days<p.min_return_days?result('M13','fail','M13_RETURN_WINDOW_TOO_SHORT',`Return limité à ${rt.days} jours ; au moins ${p.min_return_days} demandé.`,rt.days,p.min_return_days):detectInjection(text).detected?result('M13','needs_review','M13_RETURN_TERMS_UNCLEAR','La preuve de retour contient des instructions marchandes.',rt,p.min_return_days,{fact_key}):pass('M13','Return verified pour cette ligne.',rt.days,p.min_return_days));const evaluated=out.at(-1)!;for(const reason of evaluated.reasons)reason.fact_key=fact_key;for(const evidence of evaluated.evidence){evidence.source_type=usedAnswer?'human_review':'parser';evidence.source_ref=usedAnswer?.source_ref??`${e.request_id}:line:${item.line_no}`;evidence.excerpt=text;evidence.source_hash=hash(text);evidence.field=`authorization.items[${item.line_no}].item_details`;evidence.author=usedAnswer?.actor.actor_id??null;}}
 out.push(p.require_cancellation?(a.order_cancellable==='true'?pass('M14'):a.order_cancellable==='false'?result('M14','fail','M14_CANCELLATION_UNAVAILABLE','Annulation unavailable.'):result('M14','needs_review','M14_CANCELLATION_CONDITION_UNVERIFIED','Annulation unknown.')):na('M14'));
 const deadline=p.delivery_deadline;out.push(p.fulfillment_method===null&&!deadline?na('M15'):(p.fulfillment_method!==null&&a.fulfillment_method!==p.fulfillment_method)?result('M15','fail','M15_FULFILLMENT_MISMATCH','Mode de livraison incompatible.',a.fulfillment_method,p.fulfillment_method):deadline===null?pass('M15'):a.delivery_by===null?result('M15','needs_review','M15_DELIVERY_TERMS_MISSING','Date de livraison absente.'):a.delivery_by<=deadline?pass('M15','Échéance respectée.',a.delivery_by,deadline):result('M15','fail','M15_DELIVERY_DEADLINE_MISSED','Échéance dépassée.',a.delivery_by,deadline));
 // Negation applies only to the commitment it names, never to other clauses or lines.
 const recurring=a.channel==='recurring'||a.items.some(i=>{
  const affirmative=i.item_details.normalize('NFKC').replace(/\b(?:no|without|sans)\s+(?:(?:monthly|annual)\s+)?(?:subscriptions?|renewals?)(?:\s+(?:or|and|ou|ni)\s+(?:(?:monthly|annual)\s+)?(?:subscriptions?|renewals?))*\b/gi,'');
  return /\b(?:monthly|annual|subscriptions?|renew(?:als?|s)|every\s+(?:month|year)|factur(?:ation|ing)\s+mensuelle)\b/i.test(affirmative);
 });out.push(p.forbid_recurring&&recurring?result('M16','fail','M16_RECURRING_COMMITMENT_FORBIDDEN','Engagement récurrent interdit.'):recurring?result('M16','needs_review','M16_RECURRING_CONSENT_MISSING','Engagement récurrent à confirmer.'):na('M16'));
 const lines=a.items.map(i=>{const cat=pack.itemsById.get(i.item_id as never);if(!cat)return null;const fx=i.currency==='CHF'?new Decimal(1):pack.fxByCurrency.get(i.currency)?.rate;if(!fx)return null;const x=new Decimal(i.unit_price).mul(fx).toDecimalPlaces(2,Decimal.ROUND_HALF_EVEN);return {x,cat}});out.push(lines.some(x=>x===null)?result('M17','not_evaluated','M17_CATALOGUE_REFERENCE_MISSING','Référence de prix ou taux absent.',null,null,{required:false}):lines.some(x=>x&& (x.x.lt(x.cat.unit_price_min_chf)||x.x.gt(x.cat.unit_price_max_chf)))?result('M17','needs_review','M17_CATALOGUE_PRICE_OUTLIER','Prix outside fourchette catalogue.',null,null,{resolution:'confirm_risk',fact_key:'catalogue_price'}):pass('M17','Prix dans la référence catalogue.'));
 try {if(a.items.some(i=>!Number.isInteger(i.quantity)||i.quantity<=0)||a.items.some(i=>i.currency!==a.currency))throw Error('currency');const sub=a.items.reduce((n,i)=>n.add(new Decimal(String(i.quantity)).mul(String(i.unit_price))),new Decimal(0));const total=sub.add(String(a.delivery_fee));const fx=a.currency==='CHF'?new Decimal(1):pack.fxByCurrency.get(a.currency)?.rate;if(!fx)throw Error('fx');const chf=total.mul(fx).toDecimalPlaces(2,Decimal.ROUND_HALF_EVEN);const mismatch=!chf.eq(String(a.billing_amount_chf))||!sub.eq(String(a.items_subtotal))||!total.eq(String(a.amount));out.push(mismatch?result('M19','fail','M19_TOTAL_MISMATCH','Amounts reçus différents du panier.',{subtotal:a.items_subtotal,billing:a.billing_amount_chf}, {subtotal:sub.toFixed(2),billing:chf.toFixed(2)}):pass('M19','Amounts cohérents.',chf.toFixed(2)));}catch{out.push(result('M19','not_evaluated','M19_CURRENCY_MODE_UNSUPPORTED','Amount non vérifiable.',null,null,{required:true}));}
 const texts=[m.merchant_name,a.purchase_description,...a.items.flatMap(i=>[i.item_name,i.item_details,pack.itemsById.get(i.item_id as never)?.item_description??''])];const inj=texts.map(detectInjection).find(x=>x.detected);out.push(inj?result('M20','needs_review','M20_UNTRUSTED_INSTRUCTION_DETECTED','Texte marchand non fiable détecté.',inj,null,{resolution:'confirm_risk',fact_key:'merchant_injection',source_type:'parser',source_ref:e.request_id,excerpt:inj.normalized}):pass('M20','No motif détecté dans les textes.'));
 if(!a.related_authorization_id)out.push(na('M21'));else {const prior=lastAssessment(ctx.run,a.related_authorization_id);const same=ctx.run.purchases.find(x=>x.event.authorization.authorization_id===a.related_authorization_id);const old=same?.event.authorization;const valid=Boolean(prior&&same&&old&&old.timestamp<=a.timestamp&&old.scenario_id===a.scenario_id&&old.card_id===a.card_id&&old.mandate_id===a.mandate_id&&old.profile_id===a.profile_id&&same.event.mandate.customer_id===e.mandate.customer_id);const sourceStatus=a.related_authorization_status;out.push(valid?pass('M21','Devis lié ; delta courant recalculé.',{previous:a.related_authorization_id,current:a.authorization_id,source_status:sourceStatus,changed:{merchant:old!.merchant.merchant_id!==m.merchant_id,amount:old!.billing_amount_chf!==a.billing_amount_chf,items:old!.items.length!==a.items.length}}):result('M21','needs_review',same?'M21_REQUOTE_CONTEXT_MISMATCH':'M21_REQUOTE_REFERENCE_UNRESOLVED',same?'Le contexte du devis lié ne correspond pas à cette demande.':'Référence du devis non resolved.',a.related_authorization_id,null,{resolution:'provide_evidence',fact_key:'M21:reference'}));}
 const priority:Record<string,number>={fail:5,needs_review:4,not_evaluated:3,pass:2,not_applicable:1};
 const merged=new Map<string,FilterResult>();
 const score=(value:FilterResult['outcome']):number=>priority[value] ?? 0;
 for(const item of out){const old=merged.get(item.filter_id);if(!old){merged.set(item.filter_id,item);continue;} const chosen=score(item.outcome)>score(old.outcome)?item:old; merged.set(item.filter_id,{...chosen,reasons:[...old.reasons,...item.reasons],evidence:[...old.evidence,...item.evidence],depends_on:[...new Set([...old.depends_on,...item.depends_on])]});}
 const ids=['M01','M02','M03','M04','M05','M06','M07','M08','M09','M10','M11','M12','M13','M14','M15','M16','M17','M19','M20','M21'] as const;
 for(const id of ids)if(!merged.has(id))merged.set(id,na(id));
 return ids.map(id=>merged.get(id)!);
}
