import {OperationJournal} from './operation-state.js';
import type {WalletPreparation,WalletRunView} from '../../../packages/contracts/src/wallet.js';
import type {RunView} from '../../../packages/contracts/src/index.js';
import {parsePermissionJson} from './wallet-ui.js';
import {mountRunPage} from './wallet-run-controller.js';
import {habitLearningPreference,setHabitLearningPreference} from './behavior-learning-ui.js';
const app=document.querySelector<HTMLElement>('#app')!;
const flash=document.querySelector<HTMLElement>('#flash-region')!;
const journal=new OperationJournal(sessionStorage);
const esc=(v:unknown)=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
const money=(n:string|number)=>new Intl.NumberFormat('en-CH',{minimumFractionDigits:2,maximumFractionDigits:2}).format(Number(n));
let timer:ReturnType<typeof setTimeout>|undefined;
let disposeRun:(()=>void)|undefined;
let csrf='';let generation=0;
type Options={scenarios:Array<{scenario_id:string;scenario_name:string;instruction:string}>;model:string;ai_configured:boolean;live_configured:boolean};
class ApiError extends Error{constructor(readonly status:number,readonly code:string,message:string){super(message);}}
async function api<T>(path:string,init?:RequestInit):Promise<T>{let response:Response;try{response=await fetch(path,init);}catch{throw new Error('Connection interrupted. Retry this request to recover its result.');}const body=await response.json().catch(()=>({}));if(!response.ok)throw new ApiError(response.status,body.error?.code??'request_failed',body.error?.message??'The request could not be completed.');return body as T;}
async function session(scenarioId:string){csrf=(await api<{csrf:string}>(`/api/wallet/session?scenario_id=${encodeURIComponent(scenarioId)}`)).csrf;}
async function mutate<T>(path:string,body:unknown):Promise<T>{const operation=journal.begin(path,'POST',body);try{const result=await api<T>(path,{method:'POST',headers:{'content-type':'application/json','idempotency-key':operation.key,'x-csrf-token':csrf},body:operation.body});journal.acknowledged(operation);return result;}catch(error){if(error instanceof ApiError&&error.status<500)journal.acknowledged(operation);throw error;}}
function notice(error:unknown){const message=error instanceof Error?error.message:'Please try again.';flash.innerHTML=`<div class="notice notice--warning" role="status"><p>${esc(message)}</p></div>`;}
async function action(button:HTMLButtonElement,work:()=>Promise<void>){button.disabled=true;flash.innerHTML='';try{await work();}catch(error){notice(error);}finally{button.disabled=false;}}
function json(value:unknown){return `<pre class="json-view">${esc(JSON.stringify(value,null,2))}</pre>`;}
async function route(){generation++;clearTimeout(timer);disposeRun?.();disposeRun=undefined;app.setAttribute('aria-live','polite');app.setAttribute('aria-busy','true');flash.innerHTML='';try{const p=location.pathname.split('/').filter(Boolean);if(!p.length||location.pathname==='/wallet')await home();else if(location.pathname==='/wallet/new'||p[0]==='scenarios')await wizard(p[0]==='scenarios'?p[1]:undefined);else if(p[0]==='wallet'&&p[1]==='runs'&&p[2])await runPage(p[2]);else if(p[0]==='simulations'&&p[1])await runPage(p[1]);else if(p[0]==='runs'&&p[1])await inspection(p[1]);else if(p[0]==='safety'){app.innerHTML='<h1>Review your spending permissions</h1><p>Start the simplified permission review from a scenario.</p><a class="button" href="/">Choose a scenario</a>';}else throw Error('This page could not be found.');}catch(e){app.innerHTML='<section class="panel"><div class="panel__body"><h1>Let’s reconnect</h1><p>The page could not be loaded. Your saved activity is preserved.</p><button class="button" id="reload-page">Try again</button></div></section>';notice(e);document.querySelector('#reload-page')?.addEventListener('click',()=>void route());}finally{app.setAttribute('aria-busy','false');}}
async function home(){const [o,recent]=await Promise.all([api<Options>('/api/wallet/options'),api<{runs:WalletRunView[]}>('/api/wallet/runs')]);document.title='Wallet control | Viseca';app.innerHTML=`<header class="wallet-hero"><p class="eyebrow">Your agent. Your rules.</p><h1>Shop with confidence.<br>Stay in control.</h1><p>Tell us what your agent can buy. Review the permissions once. We check every purchase and ask you only when it matters.</p><a class="button" href="/wallet/new?scenario_id=SCEN0001">Set my spending permissions</a></header><section class="section-block"><div class="section-heading"><h2>Try a shopping scenario</h2><p>Synthetic purchases from the Viseca challenge.</p></div><div class="wallet-options">${o.scenarios.map(s=>`<a class="wallet-option" href="/wallet/new?scenario_id=${esc(s.scenario_id)}"><span class="mono">${esc(s.scenario_id)}</span><strong>${esc(s.scenario_name)}</strong><span>${esc(s.instruction)}</span><span class="wallet-option__action">Review permissions →</span></a>`).join('')}</div></section>${recent.runs.length?`<section class="section-block"><h2>Your recent activity</h2><div class="wallet-options">${recent.runs.map(r=>`<a class="wallet-option" href="/wallet/runs/${esc(r.run_id)}"><strong>${esc(r.scenario_id)} · ${r.mode==='local'?'Local simulation':'Viseca simulator'}</strong><span>${esc(r.status.replaceAll('_',' '))} · CHF ${money(r.approved_chf)} approved</span></a>`).join('')}</div></section>`:''}`;}
async function wizard(preselected?:string){const o=await api<Options>('/api/wallet/options');const id=preselected??new URLSearchParams(location.search).get('scenario_id')??o.scenarios[0]!.scenario_id;const s=o.scenarios.find(x=>x.scenario_id===id)??o.scenarios[0]!;await session(s.scenario_id);const saved=sessionStorage.getItem(`wallet-instruction:${id}`);app.innerHTML=`<div class="wallet-flow"><a class="back-link" href="/">← All scenarios</a><div class="flow-steps" aria-label="Progress"><span class="active">1 · Your instruction</span><span>2 · Review JSON</span><span>3 · Purchase activity</span></div><header class="page-header"><h1>What can your agent buy?</h1><p>${esc(s.scenario_name)} · Describe the limits. You will review everything before it starts.</p></header><section class="panel wallet-form"><label for="wallet-instruction">Your instruction</label><textarea id="wallet-instruction" rows="5">${esc(saved??s.instruction)}</textarea><div class="wallet-mode"><label><input type="radio" name="mode" value="local" checked> Local simulation</label><label><input type="radio" name="mode" value="live" ${o.live_configured?'':'disabled'}> Viseca simulator ${o.live_configured?'':'— access not configured'}</label></div><p class="help-text">${o.ai_configured?'AI decodes your instruction into JSON. Review it before starting.':'AI is not configured. A local parser can prepare permissions for your review.'}</p><button class="button" id="prepare-wallet">${journal.pending('/api/wallet/prepare')?'Retry saved request':'Decode instruction'}</button><p id="wallet-status" role="status" aria-live="polite"></p></section><div id="wallet-prep"></div></div>`;document.title='Your permissions | Viseca';const input=document.querySelector<HTMLTextAreaElement>('#wallet-instruction')!;input.addEventListener('input',()=>{sessionStorage.setItem(`wallet-instruction:${id}`,input.value);document.querySelector('#wallet-prep')!.innerHTML='';sessionStorage.removeItem(`wallet-preparation:${id}`);});const button=document.querySelector<HTMLButtonElement>('#prepare-wallet')!;button.addEventListener('click',()=>void action(button,async()=>{const pending=journal.pending('/api/wallet/prepare');const body=pending?.body?JSON.parse(pending.body):{scenario_id:id,instruction:input.value,mode:document.querySelector<HTMLInputElement>('input[name="mode"]:checked')!.value};document.querySelector('#wallet-status')!.textContent='Reading your instruction and checking its meaning…';document.querySelector('#wallet-prep')!.innerHTML='';const prep=await mutate<WalletPreparation>('/api/wallet/prepare',body);sessionStorage.setItem(`wallet-preparation:${id}`,prep.preparation_id);await pollPreparation(prep.preparation_id,generation);}));const prepId=sessionStorage.getItem(`wallet-preparation:${id}`);if(prepId)await pollPreparation(prepId,generation);}
async function pollPreparation(id:string,token:number){if(token!==generation)return;const p=await api<WalletPreparation>(`/api/wallet/preparations/${encodeURIComponent(id)}`);if(token!==generation)return;if(p.status==='processing'){document.querySelector('#wallet-status')!.textContent='Reading your instruction and checking its meaning…';timer=setTimeout(()=>void pollPreparation(id,token).catch(notice),900);return;}document.querySelector('#wallet-status')!.textContent=p.status==='ready'?(p.clarifications.some(c=>c.key.startsWith('unresolved:'))?'The decoder could not map every constraint to an executable rule. See the details below.':'Ready to review. Nothing starts until you confirm.'):'Your instruction is saved. You can try decoding again.';renderPreparation(p);}
function renderPreparation(p:WalletPreparation){
 const host=document.querySelector<HTMLElement>('#wallet-prep')!;
 if(p.status!=='ready'||!p.config){host.innerHTML=`<section class="notice notice--warning"><h2>Decoding unavailable</h2><p>${esc(p.error??'Reliable permissions could not be prepared.')}</p><p>Edit the instruction or decode it again.</p></section>`;return;}
 const storageKey=`wallet-json:${p.preparation_id}`;
 const source=sessionStorage.getItem(storageKey)??JSON.stringify(Object.assign({min_order_chf:null,learn_confirmed_habits:false},p.config.parameters),null,2);
 const unresolved=p.clarifications.filter(c=>c.key.startsWith('unresolved:')).map(c=>c.diagnostic??{field:c.key.slice('unresolved:'.length),reason:c.label});
 const diagnostics={...(unresolved.length?{unmapped_constraints:unresolved}:{}),...(p.warnings.length?{notes:p.warnings}:{})};
 host.innerHTML=`<section class="panel wallet-json-review"><h2>Review permission JSON</h2><p>${unresolved.length?'Some constraints have no executable rule yet. Decoding details identify them below.':'These are the parameters used by the engine. Confirming starts the run.'}</p><form id="confirm-form"><label for="permission-json">Permission JSON</label><textarea id="permission-json" class="permission-json" spellcheck="false" autocapitalize="off" autocomplete="off" wrap="off" rows="24" required>${esc(source)}</textarea><label class="confirmation-check" for="learn-confirmed-habits"><input type="checkbox" id="learn-confirmed-habits" aria-describedby="habit-learning-description habit-learning-status"> Learn my confirmed habits</label><p class="help-text" id="habit-learning-description">Use only risk checks I explicitly confirm for purchases that are finally approved. Learn device, purchase-time and merchant-country habits after confirmations on at least 3 different days. Confirmations expire after 90 days. Spending limits, explicit time rules and other permissions stay unchanged.</p><p class="help-text" id="habit-learning-status" role="status"></p><div class="button-row"><button type="button" class="button button--secondary" id="format-json">Format JSON</button><button type="submit" class="button button--confirm" id="confirm-wallet" ${unresolved.length?'disabled':''}>Confirm JSON and start</button></div><p class="help-text">${p.mode==='local'?'Local simulation. No real money moves.':'Starts a run on the Viseca simulator.'}</p></form>${p.warnings.length||unresolved.length?`<details class="technical-details" ${unresolved.length?'open':''}><summary>${unresolved.length?'Unmapped constraints':'Decoder notes'}</summary>${json(diagnostics)}</details>`:''}</section>`;
 const input=document.querySelector<HTMLTextAreaElement>('#permission-json')!;
 const learning=document.querySelector<HTMLInputElement>('#learn-confirmed-habits')!;
 const learningStatus=document.querySelector<HTMLElement>('#habit-learning-status')!;
 const syncLearning=()=>{try{learning.checked=habitLearningPreference(input.value);learning.disabled=false;learningStatus.textContent='';}catch{learning.checked=false;learning.disabled=true;learningStatus.textContent='Fix the permission JSON to review or change habit learning.';}};
 const saveReview=()=>{sessionStorage.setItem(storageKey,input.value);syncLearning();};
 input.addEventListener('input',saveReview);
 learning.addEventListener('change',()=>{try{input.value=setHabitLearningPreference(input.value,learning.checked);saveReview();}catch(error){syncLearning();notice(error);}});
 syncLearning();
 document.querySelector<HTMLButtonElement>('#format-json')!.addEventListener('click',()=>{try{input.value=JSON.stringify(parsePermissionJson(input.value),null,2);saveReview();flash.innerHTML='';}catch(error){syncLearning();notice(error);}});
 document.querySelector<HTMLFormElement>('#confirm-form')!.addEventListener('submit',event=>{event.preventDefault();if(unresolved.length)return;const button=document.querySelector<HTMLButtonElement>('#confirm-wallet')!;void action(button,async()=>{const parameters=parsePermissionJson(input.value);const result=await mutate<{run_id:string}>(`/api/wallet/preparations/${p.preparation_id}/confirm`,{confirmed:true,parameters});location.href=`/wallet/runs/${encodeURIComponent(result.run_id)}`;});});
}
async function runPage(id:string){await mountRunPage({host:app,runId:id,load:()=>api<WalletRunView>(`/api/wallet/runs/${encodeURIComponent(id)}`),openSession:session,mutate,pendingRequest:path=>journal.pending(path),notice,clearNotice:()=>{flash.innerHTML='';},onDispose:dispose=>{disposeRun=dispose;}});}
async function inspection(id:string){const v=await api<RunView>(`/api/runs/${id}`);app.innerHTML=`<a href="/" class="back-link">← Wallet home</a><header class="page-header"><p class="eyebrow">Saved inspection</p><h1>${esc(v.run.scenario_id)} · ${esc(v.run.status)}</h1><p>This historical inspection did not make payment decisions.</p></header><section class="panel"><div class="panel__body"><p>${v.counts.emitted} purchases recorded</p><blockquote>${esc(v.run.mandate_snapshot.instruction)}</blockquote><details><summary>Saved inspection data</summary>${json(v)}</details></div></section>`;}
window.addEventListener('popstate',()=>void route());void route();
