import {filterName,filterMessage} from '../../../packages/contracts/src/filter-messages.js';
import type {Assessment,Question} from '../../../packages/contracts/src/simulation.js';
import type {WalletRunView} from '../../../packages/contracts/src/wallet.js';
import {retryEligible,canConfirmQuestions} from './wallet-ui.js';

const esc=(v:unknown)=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
const money=(n:string|number)=>new Intl.NumberFormat('en-CH',{minimumFractionDigits:2,maximumFractionDigits:2}).format(Number(n));
const json=(value:unknown)=>`<pre class="json-view">${esc(JSON.stringify(value,null,2))}</pre>`;
const permissionChangeNeeded=(a:Assessment)=>a.questions.some(q=>q.state==='open'&&q.kind==='amend_mandate');
const permissionsLink=(scenarioId?:string)=>`<a class="button button--secondary" href="/wallet/new${scenarioId?`?scenario_id=${esc(encodeURIComponent(scenarioId))}`:''}">Review permissions for a new run</a>`;
const stateLabel=(a:Assessment|null)=>!a?'Processing':a.execution_state==='awaiting_user'&&!canConfirmQuestions(a.questions.filter(q=>q.state==='open'))?(permissionChangeNeeded(a)?'Permissions need review':'Verification needed'):({approved:'Approved',declined:'Declined',awaiting_user:'Needs your review',technical_hold:'Paused for verification',expired:'Confirmation expired',cancelled:'Cancelled',evaluating:'Checking'}[a.execution_state]);
export function reasonText(a:Assessment,q?:Question):string {
 if(!q&&a.execution_state==='cancelled')return 'You rejected this purchase. It was not approved.';
 if(!q&&a.execution_state==='expired')return 'The confirmation window expired. This purchase was not approved.';
 if(q){const r=a.results.flatMap(r=>r.reasons.map(reason=>({id:r.filter_id,reason,e:r.evidence.find(e=>reason.evidence_ids.includes(e.id))}))).find(x=>x.reason.fact_key===q.fact_key);return r?filterMessage(r.id,r.reason.code,r.e?.observed,r.e?.expected).replace(/^[MCG]\d{2}: /,''):q.prompt;}
 return a.results.flatMap(r=>r.reasons.filter(reason=>(a.decision==='deny'?reason.effect==='deny':reason.effect!=='none')&&r.filter_id!=='C25').map(reason=>{const e=r.evidence.find(e=>reason.evidence_ids.includes(e.id));return filterMessage(r.filter_id,reason.code,e?.observed,e?.expected).replace(/^[MCG]\d{2}: /,'');})).filter((x,i,list)=>list.indexOf(x)===i).join(' ');
}
export function renderReview(a:Assessment,authorizationId:string,mode:string,revoked=false,scenarioId?:string):string {
 if(revoked||a.execution_state!=='awaiting_user'||a.decision!=='step_up')return '';
 const questions=a.questions.filter(q=>q.state==='open');
 const confirmable=canConfirmQuestions(questions);
 const reasons=[...new Set(questions.map(q=>reasonText(a,q)))];
 const amend=permissionChangeNeeded(a);
 const resolution=amend?'This purchase cannot be confirmed under the current permissions. Review the rule and confirm new permissions to start a new run.':questions.some(q=>q.kind==='replace_quote')?'A corrected offer is needed before this purchase can be approved. Confirming the other alerts would not resolve it.':'Required information or a service must be verified before this purchase can be approved.';
 return `<section class="customer-review"><h3>${confirmable?'Review this purchase':amend?'Permissions need review':'Verification needed'}</h3><div class="consent-countdown" role="timer" aria-live="off" data-review-type="${confirmable?'confirmation':'resolution'}" data-expires-at="${esc(a.lock?.expires_at)}"><span class="countdown-label">${confirmable?'Time left to confirm':'Time until this request expires'}</span><strong class="countdown-value">—</strong></div><ul class="review-reasons">${reasons.map(r=>`<li>${esc(r)}</li>`).join('')}</ul><form class="human-form" data-authorization="${esc(authorizationId)}">${confirmable?`<div class="review-fields">${questions.filter(q=>q.kind!=='confirm_risk').map(q=>`<fieldset><legend>${esc(reasonText(a,q))}</legend><label>Verified value<input name="value:${esc(q.question_id)}" required></label><label>Where did you verify it?<input name="source_ref:${esc(q.question_id)}" required></label><label>Exact supporting text<textarea name="source_excerpt:${esc(q.question_id)}" required></textarea></label></fieldset>`).join('')}</div>${questions.some(q=>q.kind==='confirm_risk')?'<p>Confirm that you initiated this purchase and accept the risks listed above.</p>':''}`:`<p>${resolution}</p>`}<div class="review-actions">${confirmable?'<button class="button button--confirm" type="submit" data-review-action="approve">Confirm this purchase</button>':amend?permissionsLink(scenarioId):''}<button type="button" class="button button--secondary decline-purchase" data-review-action="decline" data-authorization="${esc(authorizationId)}">${mode==='live'?'Decline this purchase':'Reject this purchase'}</button></div></form></section>`;
}
export function renderHabitLearning(a:Assessment):string {
 const learning=a.behavior_learning;
 if(!learning?.enabled)return '';
 const habits=learning.profile.habits;
 const learned=habits.filter(h=>h.learned).length;
 const progress=habits.length?`${learned} learned · ${habits.length-learned} still learning`:'No confirmed habits yet';
 const applied=learning.applied_filter_ids.map(id=>filterName(id)).join(', ');
 const saved=a.execution_state==='approved'&&learning.confirmations.length>0;
 return `<section class="habit-learning" aria-label="Confirmed habit learning"><p><strong>Habits at this check:</strong> ${esc(progress)}.</p>${learning.profile.warning?`<p class="help-text">${esc(learning.profile.warning)}</p>`:''}${applied?`<p class="help-text">Learned habits were used for this check: ${esc(applied)}. Spending limits and all other checks still apply.</p>`:''}${saved?'<p class="help-text">Confirmation saved for future habit learning.</p>':''}<details class="technical-details" data-detail="habit-learning"><summary>Learning details</summary><p>Profile ${esc(learning.profile.version)} · Snapshot ${esc(learning.profile.as_of)}</p>${habits.length?`<ul>${habits.map(h=>`<li>${esc(filterName(h.filter_id))} · ${esc(h.context_key)}: ${h.confirmations} confirmations on ${h.distinct_days} different days · ${h.learned?'Learned':'Still learning'}</li>`).join('')}</ul>`:'<p>This profile had no confirmed habits when this purchase was checked.</p>'}<p class="help-text">Only explicit risk confirmations for purchases that were approved count. Learning requires at least 3 different days. Confirmations expire after 90 days. This snapshot is kept with the decision; new confirmations apply to future checks.</p>${json(learning.profile)}</details></section>`;
}
export function renderPurchaseCard(p:WalletRunView['purchases'][number],mode:string,runStatus:string,scenarioId?:string):string {
 const a=p.assessment;
 const amend=!!a&&permissionChangeNeeded(a);
 const expiredPermissions=a&&amend&&['expired','technical_hold'].includes(a.execution_state)&&runStatus!=='revoked';
 return `<article class="purchase-card" data-purchase="${esc(p.authorization_id)}" aria-label="${esc(p.merchant_name)} · CHF ${money(p.amount_chf)}"><div class="purchase-heading"><div><h2>${esc(p.merchant_name)}</h2><p>${esc(p.description)}</p></div><div class="purchase-price"><strong>CHF ${money(p.amount_chf)}</strong><span class="badge ${a?.decision==='approve'?'badge--success':a?.decision==='deny'?'badge--danger':'badge--warning'}">${esc(stateLabel(a))}</span></div></div>${mode==='live'?`<p class="help-text">Platform: ${esc(p.platform_status??'awaiting result')}</p>`:''}${a&&a.decision!=='approve'&&a.execution_state!=='awaiting_user'?`<p class="purchase-reason">${esc(reasonText(a))}</p>`:''}<ul class="basket-lines">${p.items.map(i=>`<li><strong>${i.quantity} × ${esc(i.item_name)}</strong><span>${esc(i.item_details)}</span></li>`).join('')}</ul>${a?renderReview(a,p.authorization_id,mode,runStatus==='revoked',scenarioId):''}${expiredPermissions?`<section class="customer-review"><h3>Permissions need review</h3><ul class="review-reasons">${a.questions.filter(q=>q.state==='open'&&q.kind==='amend_mandate').map(q=>`<li>${esc(reasonText(a,q))}</li>`).join('')}</ul><p>Re-evaluating with the same permissions would keep this purchase blocked. Review the rule and confirm new permissions to start a new run.</p>${permissionsLink(scenarioId)}</section>`:''}${a?renderHabitLearning(a):''}${runStatus!=='revoked'&&!amend&&retryEligible(a,mode)?`<button class="button button--secondary retry-purchase" data-authorization="${esc(p.authorization_id)}">Re-evaluate purchase</button>`:''}<details class="technical-details" data-detail="decision"><summary>Why this decision? ${a?.results.length??0} safety checks</summary>${a?(['merchant','customer','guard'] as const).map(domain=>`<h3>${domain==='merchant'?'Merchant and product':domain==='customer'?'Your wallet permissions':'Execution safeguards'}</h3><div class="checks-list">${a.results.filter(r=>r.domain===domain).map(r=>`<details data-detail="${r.filter_id}"><summary><span>${r.filter_id} · ${esc(filterName(r.filter_id))}</span><span>${esc(r.outcome.replaceAll('_',' '))}</span></summary>${r.reasons.map(reason=>{const e=r.evidence.find(e=>reason.evidence_ids.includes(e.id));return `<p>${esc(filterMessage(r.filter_id,reason.code,e?.observed,e?.expected))}</p>`;}).join('')}${json(r.evidence)}</details>`).join('')}</div>`).join(''):''}<p class="mono">Authorization: ${esc(p.authorization_id)} · Merchant: ${esc(p.merchant_id)}</p></details></article>`;
}
export function purchaseSkeleton(waiting=false):string {
 return `<div class="purchase-card purchase-skeleton" ${waiting?'data-waiting-slot':''} aria-hidden="true"><div class="skeleton-line skeleton-title"></div><div class="skeleton-line skeleton-amount"></div><div class="skeleton-line"></div><div class="skeleton-line"></div><div class="skeleton-line skeleton-button"></div>${waiting?'<p>Waiting for the next proposal…</p>':''}</div>`;
}
export function runLoading():string {
 return `<div class="wallet-flow run-loading" role="status" aria-label="Loading purchase activity"><h1>Loading purchase activity…</h1><div class="wallet-summary" aria-hidden="true"><div class="skeleton-line"></div><div class="skeleton-line"></div><div class="skeleton-line"></div></div><div class="purchase-feed" aria-hidden="true">${purchaseSkeleton()}${purchaseSkeleton()}${purchaseSkeleton()}</div></div>`;
}
