import type { AuthorizationEvent, MandateSnapshot } from './event.js';
import type { HistoricalAuthorization } from './data.js';
import type { BehaviorProfile, BehaviorObservation, HabitFilterId } from './behavior.js';
import type { BehaviorJournal } from './behavior-dashboard.js';
import type { MLFeatureSnapshot } from './behavior-ml.js';
import type { BehaviorLearningComparison } from './behavior-evaluation.js';
export const MERCHANT_FILTER_IDS = ['M01','M02','M03','M04','M05','M06','M07','M08','M09','M10','M11','M12','M13','M14','M15','M16','M17','M19','M20','M21'] as const;
export const CUSTOMER_FILTER_IDS = ['C01','C02','C03','C04','C05','C06','C08','C09','C10','C11','C12','C13','C14','C15','C16','C18','C19','C20','C22','C24','C25','C26'] as const;
export const GUARD_FILTER_IDS = ['G01','G02','G03','G04','G05','G06','G07','G08'] as const;
export const ACTIVE_FILTER_IDS = [...MERCHANT_FILTER_IDS,...CUSTOMER_FILTER_IDS,...GUARD_FILTER_IDS] as const;
export type FilterId = typeof ACTIVE_FILTER_IDS[number];
export type Phase = 'prepare'|'assess'|'resolve'|'commit';
export type Outcome = 'pass'|'fail'|'needs_review'|'not_applicable'|'not_evaluated';
export type Evidence = { id:string; source_type:'event'|'catalogue'|'history'|'mandate'|'ledger'|'parser'|'model_proposal'|'human_review'; source_ref:string; field:string; source_hash:string; excerpt:string|null; observed:unknown; expected:unknown; method:string; author:string|null };
export type Reason = { code:string; message:string; effect:'deny'|'step_up'|'technical_hold'|'none'; certainty:'established'|'uncertain'|'unavailable'; evidence_ids:string[]; requirement_ids:string[]; resolution_kind:'provide_evidence'|'choose_variant'|'confirm_risk'|'confirm_requirement'|'amend_mandate'|'replace_quote'|'retry_or_repair'|'none'; fact_key:string };
export type FilterResult = { filter_id:FilterId; domain:'merchant'|'customer'|'guard'; kind:'hard_requirement'|'integrity'|'review_signal'|'information'; phase_expected:Phase[]; phase_evaluated:Phase|null; required_at_current_phase:boolean; outcome:Outcome; coverage:'available'|'partial'|'unavailable'; reasons:Reason[]; evidence:Evidence[]; question_ids:string[]; depends_on:FilterId[]; algorithm_version:string };
export type Requirement = { requirement_id:string; source_excerpt:string; description:string; filter_ids:FilterId[]; parameter_keys:string[]; status:'pending'|'confirmed'; question:string|null; author:string|null; revision:number };
export type SafetyParameters = {
  learn_confirmed_habits?:boolean;
  manual_review_requirements?:Array<{source_excerpt:string;description:string}>;
  min_order_chf:string|null; max_order_chf:string|null; rolling_budget:{limit_chf:string; days:number}|null; daily_budget_chf:string|null; monthly_budget_chf:string|null;
  allowed_currencies:string[]|null; allowed_merchant_ids:string[]|null; blocked_merchant_ids:string[]; allowed_merchant_categories:string[]|null; allowed_merchant_countries:string[]|null;
  familiar_merchant:boolean; bounded_history_required:boolean; regularity:{days:number; distinct_dates:number}|null;
  allowed_item_categories:string[]|null; allowed_item_ids:string[]|null; product_type:string|null;
  attributes:Array<{name:'size'|'color'|'inches'; values:string[]; unit:string|null}>; numeric_size_convention:string|null;
  no_extras:boolean; max_quantity_per_order:number|null; mission_quantity:number|null; min_return_days:number|null; require_cancellation:boolean; fulfillment_method:string|null; delivery_deadline:string|null; forbid_recurring:boolean;
  domestic_country:string|null; account_purpose:string|null; watch_devices:boolean; burst_threshold:number|null; duplicate_hours:number|null;
  time_review:{from_hour:number; to_hour:number}|null; historical_time_review:boolean; unusual_country:boolean; unusual_amount:boolean; preference_categories:string[];
  always_ask:boolean; autonomous_limit_chf:string|null; consent_ttl_seconds:number; timezone:string;
};
export type SafetyConfig = { schema_version:1; config_id:string; mandate_id:string; mandate_version:number; revision:number; instruction:string; instruction_hash:string; status:'draft'|'confirmed'; requirements:Requirement[]; parameters:SafetyParameters; confirmed_by:string|null; confirmed_at:string|null; created_at:string };
export type HumanActor = { actor_id:string; role:'simulated_human'; customer_id:string; channel:'local_ui'; authenticated_by_server:true };
export type Question = { question_id:string; fact_key:string; kind:Reason['resolution_kind']; filter_ids:FilterId[]; evidence_ids:string[]; prompt:string; offer_hash:string; state:'open'|'resolved'; answer_id:string|null };
export type HumanAnswer = { answer_id:string; question_id:string; fact_key:string; kind:Question['kind']; value:string; source_ref:string|null; source_excerpt:string|null; actor:HumanActor; offer_hash:string; config_revision:number; created_at:string; expires_at:string; consumed_by:string|null };
export type PurchaseLock = { lock_id:string; kind:'denied_version'|'pending_step_up'|'technical_hold'; assessment_id:string; offer_hash:string; mandate_version:number; config_revision:number; reason_filter_ids:FilterId[]; reason_codes:string[]; evidence_ids:string[]; question_ids:string[]; observed_expected:Evidence[]; created_at:string; expires_at:string|null; resolution:string };
export type Assessment = { behavior_learning?:{enabled:boolean;profile:BehaviorProfile;applied_filter_ids:HabitFilterId[];confirmations:BehaviorObservation[];comparison?:BehaviorLearningComparison;ml_features?:MLFeatureSnapshot[]}; schema_version:1; scope:'local_simulation'; assessment_id:string; run_id:string; authorization_id:string; source_authorization_id:string; revision:number; decision:'approve'|'deny'|'step_up'|null; execution_state:'evaluating'|'awaiting_user'|'technical_hold'|'approved'|'declined'|'cancelled'|'expired'; evaluation_complete:boolean; can_finalize:boolean; rule_snapshot:{mandate_id:string;mandate_version:number;config_revision:number}; event_hash:string;offer_hash:string;facts_hash:string;engine_version:string;ledger_revision:number;results:FilterResult[];blocking_filter_ids:FilterId[];doubt_filter_ids:FilterId[];technical_filter_ids:FilterId[];evidence:Evidence[];questions:Question[];lock:PurchaseLock|null;recorded_at:string;scenario_timestamp:string;correlation_id:string };
export type Commitment = {authorization_id:string;amount_chf:string;timestamp:string;quantity:number;budget_scope_id:string};
export type Reservation = Commitment & {offer_hash:string;expires_at:string};
export type AuditEntry = {sequence:number;at:string;scenario_timestamp:string|null;actor:string;event:string;authorization_id:string|null;assessment_id:string|null;filter_ids:FilterId[];details:unknown;correlation_id:string};
export type SimPurchase = {event:AuthorizationEvent;assessments:Assessment[];answers:HumanAnswer[]};
export type SimRun = {schema_version:1;scope:'local_simulation';run_id:string;run_key:string;scenario_id:string;customer_id:string;card_id:string;authority_id:string;mandate_snapshot:MandateSnapshot;mandate_version:number;config:SafetyConfig;budget_scope_id:string;status:'active'|'completed'|'revoked';next_index:number;revision:number;history:HistoricalAuthorization[];history_hash:string;history_coverage:{from:string;to:string;rows:number};purchases:SimPurchase[];commitments:Commitment[];reservations:Reservation[];audit:AuditEntry[];created_at:string};
export type SimulationDocument = {schema_version:1;configs:SafetyConfig[];runs:SimRun[];commands:Record<string,{fingerprint:string;response:unknown}>;behavior_journal?:BehaviorJournal};
