import type { FastifyInstance,FastifyRequest } from 'fastify';
import type { LocalRuntime } from '../../../packages/local-runtime/src/runtime.js';
import type { HumanChannel } from './human-channel.js';
import { AppError } from '../../../packages/contracts/src/errors.js';
import { strictObject,requiredString } from './request-validation.js';
export function registerWalletRoutes(app:FastifyInstance,runtime:()=>LocalRuntime,channel:HumanChannel):void{
 const key=(req:FastifyRequest)=>{const value=req.headers['idempotency-key'];if(typeof value!=='string'||!/^[A-Za-z0-9._:-]{8,200}$/.test(value))throw new AppError(400,'G01_IDEMPOTENCY_KEY_REQUIRED','A request key is required.');return value;};
 app.get('/api/wallet/options',async()=>runtime().wallet.options());
 app.get<{Querystring:{scenario_id:string}}>('/api/wallet/session',async(req,reply)=>channel.issue(runtime().wallet.actorCustomer(req.query.scenario_id),reply));
 app.post('/api/wallet/prepare',async(req,reply)=>{const b=strictObject(req.body,['scenario_id','instruction','mode']);const a=channel.actor(req);const scenario_id=requiredString(b['scenario_id'],'scenario_id');if(a.customer_id!==runtime().wallet.actorCustomer(scenario_id))throw new AppError(403,'customer_mismatch','Open this scenario before preparing permissions.');if(b['mode']!=='local'&&b['mode']!=='live')throw new AppError(400,'mode_invalid','Choose local simulation or Viseca.');const p=runtime().wallet.prepare({scenario_id,instruction:requiredString(b['instruction'],'instruction'),mode:b['mode']},key(req));reply.code(202);return p;});
 app.get<{Params:{id:string}}>('/api/wallet/preparations/:id',async req=>runtime().wallet.getPreparation(req.params.id));
 app.post<{Params:{id:string}}>('/api/wallet/preparations/:id/confirm',async req=>{key(req);const b=strictObject(req.body,['confirmed','parameters']);if(b['confirmed']!==true)throw new AppError(422,'customer_confirmation_required','Please review the permissions and confirm before starting.');const values=b['parameters'];if(values===null||typeof values!=='object'||Array.isArray(values))throw new AppError(400,'parameters_invalid','Permission JSON must be an object.');return runtime().wallet.confirm(req.params.id,values as Record<string,unknown>,channel.actor(req));});
 app.get('/api/wallet/runs',async()=>({runs:runtime().wallet.listRuns()}));
 app.get<{Params:{id:string}}>('/api/wallet/runs/:id',async req=>runtime().wallet.getRun(req.params.id));
 app.post<{Params:{id:string}}>('/api/wallet/runs/:id/revoke',async req=>{strictObject(req.body??{},[]);return runtime().wallet.revoke(req.params.id,channel.actor(req),key(req));});
 app.post<{Params:{id:string}}>('/api/wallet/runs/:id/human-responses',async req=>{key(req);const b=strictObject(req.body,['authorization_id','decision','answers']);if(b['decision']!=='approve'&&b['decision']!=='decline')throw new AppError(400,'decision_invalid','Choose approve or decline.');if(!Array.isArray(b['answers']))throw new AppError(400,'answers_invalid','Responses must be a list.');const answers=b['answers'].map(value=>{const a=strictObject(value,['question_id','value','source_ref','source_excerpt']);return {question_id:requiredString(a['question_id'],'question_id'),value:requiredString(a['value'],'value'),...(a['source_ref']===undefined?{}:{source_ref:requiredString(a['source_ref'],'source_ref')}),...(a['source_excerpt']===undefined?{}:{source_excerpt:requiredString(a['source_excerpt'],'source_excerpt')})};});return runtime().wallet.respondLive(req.params.id,{authorization_id:requiredString(b['authorization_id'],'authorization_id'),decision:b['decision'],answers},channel.actor(req));});
}
